### ISSUE TITLE
Webpack project not detecting changes

### ISSUE THREAD

**Issue by lmartins** [wallabyjs/console-ninja#1]
Project seems to be patched as I am seeing the logs being appended with a string at the end:
https://share.cleanshot.com/HxIQq6

However the status bar indicates it is still waiting for a connection: https://share.cleanshot.com/LL7Djy

I've tried placing logs in several places of the codebase, some that run immediately some that run upon user interaction. None seems to trigged Console Ninja to detect the new log.

Any clues to what I should try next?

**Comment by ArtemGovorov** [comment]
Hey, thanks for trying the tool!

Please try
- restart your IDE and webpack process;
- refresh your browser;
- try adding logs again to check if it helps.

If it doesn't help, please share:
- your browser version,
- the address/URL that you are using (is it localhost or something else)?
- attach your `~/.console-ninja/trace.log` file.

**Comment by lmartins** [comment]
Thank you @ArtemGovorov  

I've tried the suggested steps, doesn't seem to make a difference.

As for the requested info:

- Chrome Canary 110.0.54
- Running webpack's server at https://192.168.86.86:3000/
- File is attached: [trace.log](https://github.com/wallabyjs/console-ninja/files/10183697/trace.log)

Thanks again!

**Comment by ArtemGovorov** [comment]
> Running webpack's server at https://192.168.86.86:3000/

Thanks!

Right now for [security reasons](https://github.com/wallabyjs/console-ninja#how-does-it-work) we limit allowed hosts to `localhost` and `127.0.0.1`. If it's possible for you to run from `localhost` or `127.0.0.1`, then it should work. Otherwise we may add a setting to allow more host addresses in future releases.

**Comment by lmartins** [comment]
@ArtemGovorov  oh that was it. With `localhost` it connects right away. Thanks so much for your help.
