### ISSUE TITLE
[Feature]: support for fusebox

### ISSUE THREAD

**Issue by tarwich** [wallabyjs/console-ninja#103]
### Describe the feature you'd like.

We're using [fusebox](https://github.com/fuse-box/fuse-box) as our bundler. Is there any way to add support for it?

I've been holding off mentioning it in hopes you'd come out with a library I could add or call. Especially since I'm trying to convince the company to use a different bundler in the next few years. 

If you're able to add support for it, it would help with our development cycle. Thanks!

**Comment by smcenlly** [comment]
Looking at contributions, website, and npm downloads, it looks like [fusebox](https://github.com/fuse-box/fuse-box) is a legacy/deprecated technology and as such is not something we will support as a first class technology:

**github contributions**
<img width="895" alt="image" src="https://user-images.githubusercontent.com/2074089/219226108-d6a81ec4-fc21-4df9-a9b9-d85f8860e93b.png">

**website**
<img width="575" alt="image" src="https://user-images.githubusercontent.com/2074089/219226201-3bcd6152-9123-4094-a73f-fe1d436fdfec.png">

**npm downloads**
<img width="374" alt="image" src="https://user-images.githubusercontent.com/2074089/219226270-0ff71d8c-9f6e-45c5-9807-530e50324332.png">

---

> I've been holding off mentioning it in hopes you'd come out with a library I could add or call. Especially since I'm trying to convince the company to use a different bundler in the next few years.

We are working on a feature to allow Console Ninja work with any application launched directly as `node file_name.js`, which you should be able to use to work with `fusebox`. Please track [this issue](https://github.com/wallabyjs/console-ninja/issues/47) for updates.

**Comment by tarwich** [comment]
Thanks! #47 seems to be what I was looking for.
