### ISSUE TITLE
Console ninja watches the wrong webpack with 2 projects open in Visual Studio Code

### ISSUE THREAD

**Issue by dmenne** [wallabyjs/console-ninja#104]
Windows, Visual Studio Code

- Workspace has 2 React Projects A and B.
- Working on Project A: Everything fine (super fine, this is a top tool++)
- Switch to Project B. Restart Ninja, Restart Visual Studio code, Reboot Windows, multiple restarts of webpack: all tried. Ninja Log Window comes up, but no output in Console and Editor.
- "Waiting for Webpack"
- Checking trace.log: info host  patch still refers to webpack in Project A
- Remove Project A from Workspace. Restart
- Hurray: All fine++

**Comment by smcenlly** [comment]
Thanks for your bug report.

Could you please provide us with the following details:

1. What version of Console Ninja are you using?

2. Can you confirm the physical location of the two projects on disk, are you running a multi-root workspace?

3. Your log output: please copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory after reproducing the problem.

**Comment by dmenne** [comment]
- v0.0.76
- Both directories are subdirs of a common (exercises and examples of https://fullstackopen.com/en/part2/altering_data_in_server#extracting-communication-with-the-backend-into-a-separate-module)
- First worked successfully in project phonebook, then added part2-notes  to project and started it successfully - no Ninja output
[trace.zip](https://github.com/wallabyjs/console-ninja/files/10753496/trace.zip)

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. Do you open both projects as a multi-root workspace in VS Code? If it's the case, then the scenario is not yet supported, here's the feature request to subscribe to: https://github.com/wallabyjs/console-ninja/issues/91. If you open the projects separately in separate VS Code instances, it should work (please let us know if it's not working).

**Comment by dmenne** [comment]
I see. Thanks.
