### ISSUE TITLE
[Feature]: Initiate logging via right-click context menu "Console Ninja: Log Output"

### ISSUE THREAD

**Issue by codebycarlos** [wallabyjs/console-ninja#106]
### Describe the feature you'd like.

First of all, thank you soo much for this extension. It is incredibly helpful. 🚀

One thing I find myself doing more now that I can easily see console logs right in the editor, is writing more console logs!

But what if there was a way to skip that all together. If one could highlight a variable or line of code, right-click, and select an option "Console Ninja: Log Output". Then, Console Ninja would start logging right next to it any relevant variables (no console log necessary, ironically). 

Ideally, there'd be an indicator next to the line number to let the user know visually that its contents are being logged. And of course, a way to disable the logging when done.

**Comment by ArtemGovorov** [comment]
Hey, thanks for your kind words!

> But what if there was a way to skip that all together. If one could highlight a variable or line of code, right-click, and select an option "Console Ninja: Log Output". Then, Console Ninja would start logging right next to it any relevant variables (no console log necessary, ironically).

We have released the feature you want a couple of weeks ago. Check it out: https://github.com/wallabyjs/console-ninja#logpoints.
