### ISSUE TITLE
[Feature]: Being able to change the font size

### ISSUE THREAD

**Issue by kud** [wallabyjs/console-ninja#108]
### Describe the feature you'd like.

I'd like to increase the size of the font in the log window. Thanks.

**Comment by smcenlly** [comment]
We had intentionally set the font-size to align with the rest of the editor. Before adding this as a feature request, just wanted to confirm that you're aware of VS Code's `View: Zoom In` and `View: Zoom Out` commands, as we had thought this would be sufficient (we understand this changes all font sizes).

![zoom](https://user-images.githubusercontent.com/2074089/222295750-ecf678a5-1929-410b-a31d-53e9ee990c7d.gif)

**Comment by kud** [comment]
I'm aware yes 😌

Multiple things:
- I've unzoomed a bit VS Code because I felt the icons and layout were too big for me
- I've removed the zoom shortcuts from the keyboard because I don't want to change the layout
- It's the only extension I have an issue because usually it's either already fine, either the provide a way to set the font-size.

Thank you 😌

**Comment by kud** [comment]
Also, yes I've unzoomed the layout but I've also increased the font-size of my editor so yeah you took care about the zoom but you did not regarding the font-size of the editor.

Either you let the user sets the font-size as they want either you also care about the font-size of the editor and not just the zoom of the IDE.

**Comment by smcenlly** [comment]
We have added support for setting the Console Output font size with a new setting, `console-ninja.fontSize` in the latest version of Console Ninja, `v0.0.84`.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/2074089/224224044-2be5cf6d-d245-4b98-9f68-d7303a970f1c.png">

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/2074089/224224323-958123bd-e42b-49db-aa90-fbbb397ec854.png">

**Comment by kud** [comment]
That's amazing. Thank you so much @smcenlly , I appreciate 😌
