### ISSUE TITLE
Problem with yarn berry integrations

### ISSUE THREAD

**Issue by KirillKrasuk** [wallabyjs/console-ninja#11]
Since today, I could not run the project on the yarn berry version due to problems with the extension. Removing the extension from vscode does not allow yarn to work properly at all

<img width="512" alt="image" src="https://user-images.githubusercontent.com/69843247/206479463-96d5d7bb-676b-42ce-960a-56863a04f8be.png">

**Comment by NikGovorov** [comment]
Sorry for the inconvenience, to fix the issue please delete the plugin from your ~/.yarnrc.yml file.

**Comment by KirillKrasuk** [comment]
thanks it helped

**Comment by NikGovorov** [comment]
We've fixed the issue with the broken yarn after the extension uninstall. Could you tell us what didn't work for you initially?
