### ISSUE TITLE
[Feature]: Option to turn off the automatic console errors.

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#117]
### Describe the feature you'd like.

So here's my situation. I'm currently working on a big React project where a lot of teams are contributing on the project. 
I'm only working on a small area of the React project. And since it is big team there are a lot of console errors contributed by other teams which I have no control of (and since it is not in the scope of my work I have no way of fixing it.) 

Now these console errors are more than what I needed to console.log for my own components and it's really polluting the Output on Console Ninja. And I guess it's really nice to turn this off since these errors on other part of the project is really not part of my task. 

I know it's a nice feature(outputting the errors automatically) but with such big projects I think I just want to focus on the parts where I'm just currently working on and only show console logs where I'm intended to. 

Also these unintentional console logs(these automatic error logs) I think is slowing down the extension and VS code because there's a lot of them.

**Comment by omerson-cruz** [comment]
Maybe something like what's described in this

![image](https://user-images.githubusercontent.com/65213312/226515031-5e8fe580-f0aa-4ea5-a0b4-78daf875676b.png)

**Comment by ArtemGovorov** [comment]
[Advanced Output Filtering](https://github.com/wallabyjs/console-ninja#output-filtering-pro) feature (including the setting to turn errors capturing off) has just been released in v0.0.112.

**Comment by omerson-cruz** [comment]
Awesome! Thank you so much for this feature :)

**Comment by omerson-cruz** [comment]
@NikGovorov btw just a feedback on this feature it makes the logging by ninja much faster without the unnecessary noise from other console logs in this big project that I'm currently working on. Thanks again  :)
