### ISSUE TITLE
[Bug]: Universal Node application not working

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#120]
### What happened?

I tried testing the Console Ninja with an "node" application and it's not working as described here on the Universal Node application instruction 

![image](https://user-images.githubusercontent.com/65213312/227648999-00f492e8-d590-4544-bb6e-4d0dc19f4778.png)

I'm currently on WSL ubuntu and if I try executing it. 

![image](https://user-images.githubusercontent.com/65213312/227649605-c14d56e7-93a3-4cdf-ab4c-e57a929f816d.png)

I also tried sourcing it like below and it does not work. 

![image](https://user-images.githubusercontent.com/65213312/227649779-a17842f4-4ec3-483e-9f27-480d8e9f1cbc.png)

Also I'm not sure if that "console-ninja" is a package that I should install or something?

### Version

V.0.0.87

### Steps to reproduce (or sample repo)

I followed steps as described on the instruction for Universal Node applications

https://github.com/wallabyjs/console-ninja#universal-node-applications

### Log output

```shell
info extension stopping host
info extension client disconnected: 1006 
info extension host process output: port:[35613]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 35613 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.87","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.87/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.87/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/client_orig/src/store.js"},{"path":"/home/omersonc/sbox/vue-graphql/client_orig/src/main.js"},{"path":"/home/omersonc/sbox/vue-graphql/app.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/app.ffbb0a20.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/AuthGuard.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/index.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.BKP-beforeRefactor.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Auth/Profile.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.B4VuexGQLApollo.bkp.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.ReactApolloWay.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Posts.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Post.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.bkp.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/store/index.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/chunk-vendors.33db715f.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/plugins/apollo.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/App.vue"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["nuxt"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","app.dev.entourage-events.link","regime.dev.entourage-events.link","platform.dev.entourage-events.link","platform.dev.entourage-events.link:3000","platform.entourage-events.link:3000","localhost:3000","localhost:3004","172.30.192.35"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
```

**Comment by NikGovorov** [comment]
Apparently, you don't have the XDG bin folder `$HOME/.local/bin` in `PATH`, could you please try to add `PATH=$PATH:~/.local/bin` to your `~/.bash_profile`, source it `source ~/.bash_profile` or start a new session and see if `console-ninja` is available by executing `which console-ninja`.

**Comment by omerson-cruz** [comment]
Hi @NikGovorov , thanks for your quick response. 
I've tried the steps you said and I'mnow able add console-ninja on the PATH variable. 
Though it seems it's still not working. Not sure what I'm missing. 

![image](https://user-images.githubusercontent.com/65213312/227701884-4aeb1a05-0cad-4f5d-afbe-3fc9f0bdc456.png)


Also I tried testing it with a simple hello world node file and it's not working as well like below. 

![image](https://user-images.githubusercontent.com/65213312/227701956-862e44c3-2501-4000-b776-3da0d7fd6e66.png)

**Comment by omerson-cruz** [comment]
Not sure if this can help you but here's the log content from console ninja while I'm executing that
`info host starting tools discovery and integration
info host looking for tools to patch
info host starting tools discovery and integration
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host looking for tools to patch
info host completed tools discovery and integration
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info extension stopping host
info extension host process output: port:[42057]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 42057 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.88","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.88/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.88/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/app.ffbb0a20.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/chunk-vendors.33db715f.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/AuthGuard.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/index.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.BKP-beforeRefactor.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Auth/Profile.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.B4VuexGQLApollo.bkp.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.ReactApolloWay.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Posts.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Post.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.bkp.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/store/index.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/plugins/apollo.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/App.vue"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["webpack","http-server","serve"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","app.dev.entourage-events.link","regime.dev.entourage-events.link","platform.dev.entourage-events.link","platform.dev.entourage-events.link:3000","platform.entourage-events.link:3000","localhost:3000","localhost:3004","172.17.99.15"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 1 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
`

**Comment by NikGovorov** [comment]
Could you please share a screenshot of Console Ninja status? 
![image](https://user-images.githubusercontent.com/129254/227706335-959f9df4-89c4-4453-a2e8-90bf9acb623d.png)

**Comment by r-oland** [comment]
I'm experiencing the same issue. My current status is set to inactive, and I also noticed an error in the logs:

`ERR! host failed to create symbolic link EACCES: permission denied, symlink '/Users/macbook-roland/.console-ninja/.bin/console-ninja' -> '/usr/local/bin/console-ninja'`

**Comment by NikGovorov** [comment]
> I'm experiencing the same issue. My current status is set to inactive, and I also noticed an error in the logs:
> 
> `ERR! host failed to create symbolic link EACCES: permission denied, symlink '/Users/macbook-roland/.console-ninja/.bin/console-ninja' -> '/usr/local/bin/console-ninja'`

Could you please try [this](https://github.com/wallabyjs/console-ninja/issues/120#issuecomment-1483636350) suggestion?

**Comment by r-oland** [comment]
@NikGovorov no luck unfortunately 👎

**Comment by omerson-cruz** [comment]
@NikGovorov it is currently inacitve as seen on SS below. 

https://user-images.githubusercontent.com/65213312/227721736-2d10ec2e-982d-4d81-8ef8-7d2d506cd9c2.mp4

**Comment by NikGovorov** [comment]
Please try to update to the latest version(v0.0.91) and see if it works for you.

**Comment by tuan-dd** [comment]
![image](https://user-images.githubusercontent.com/118432439/227866083-de7dfe8a-ee18-453e-839e-31159f283315.png)
i have same issue

**Comment by NikGovorov** [comment]
@tuan-dd your issue is different from the original one. `node` doesn't run Typescript file by default, try `console-ninja npx tsx .\sample.ts`

**Comment by omerson-cruz** [comment]
Hi @NikGovorov, I already updated to v0.0.91 though it's still not working :( . 
Please see my SS below. 
I tried uninstalling and reinstalling Console Ninja but it's still the same issue. I'm also posting my current logs if that would help 

https://user-images.githubusercontent.com/65213312/228067136-35ca5f43-e75d-4c76-8ca5-04e33d6d158b.mp4

`info extension stopping host
info extension client disconnected: 1006 
info extension host process output: port:[45625]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 45625 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.29.135.136"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
info host removing cache folder: 231f875645c62db3e67a9d98dc4b786f
info extension stopping host
info host removing cache folder: c87bf86309e93d4a309bcfbfe4dde3de
info extension stopping host
info host ------------ starting ------------
info host worker Starting Host Worker...
info extension host process output: port:[35613]
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 35613 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"},{"path":"/home/omersonc/sbox/vue-graphql/client_orig/src/store.js"},{"path":"/home/omersonc/sbox/vue-graphql/client_orig/src/main.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/app.ffbb0a20.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/dist/js/chunk-vendors.33db715f.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/AuthGuard.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/router/index.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.BKP-beforeRefactor.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.ReactApolloWay.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Auth/Profile.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Home.B4VuexGQLApollo.bkp.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.bkp.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Posts.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/plugins/apollo.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/components/Posts/Post.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/main.js"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/App.vue"},{"path":"/home/omersonc/sbox/vue-graphql/client/src/store/index.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.29.135.136"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host found 2 tool file(s) to patch
info host patching /home/omersonc/sbox/vue-graphql/client/node_modules/webpack/lib/webpack.js
info host patching /home/omersonc/sbox/vue-graphql/client_orig/node_modules/webpack/lib/webpack.js
info host completed tools discovery and integration
info extension stopping host
info host removing cache folder: 06b2de92b0fce4931b50431abd1ac500
info extension stopping host
info extension stopping host
info host removing cache folder: bf76e2cebd7943969afcf73e932adca6
info uninstalling yarn plugin from /home/omersonc/.yarnrc.yml
info extension stopping host
info extension host process output: port:[45625]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 45625 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.23.124.29"],"host":"localhost"}
info host starting tools discovery and integration
info host installing /home/omersonc/.local/bin/console-ninja
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
info extension stopping host
info host removing cache folder: f67a5639d3e3d4bfa9bba0bd3ba3aedf
info extension stopping host
info extension host process output: port:[45625]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 45625 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.23.124.29"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
info extension stopping host
info host removing cache folder: 809fe6534a032b4d2a96b2270e4d0106
info extension client disconnected: 1006 
info extension host process output: port:[45625]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 45625 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.23.124.29"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
info extension stopping host
info extension client disconnected: 1006 
info extension host process output: port:[45625]
info host ------------ starting ------------
info extension 
info host client connected: extension { address: '::', family: 'IPv6', port: 45625 }
info host starting host: {"extensionFolder":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91","runtimeHookFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/omersonc/.vscode-server/extensions/wallabyjs.console-ninja-0.0.91/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/omersonc/sbox/vue-graphql/api/resolvers.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/test.js"},{"path":"/home/omersonc/sbox/vue-graphql/api/server.js"}],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss","openLinksInEditor":false,"maxLogViewerEntries":20,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","nuxt","remix","qwik","hydrogen"]},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","LEGION","172.23.124.29"],"host":"localhost"}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 0 tool file(s) to patch
info host completed tools discovery and integration
info host removing cache folder: e400fa731a0e97464b242dd23d19e517
`

**Comment by NikGovorov** [comment]
@omerson-cruz, Could you please execute `cat /home/omersonc/.local/bin/console-ninja` and share the output?

**Comment by omerson-cruz** [comment]
@NikGovorov , here's the output of the command

![image](https://user-images.githubusercontent.com/65213312/228125800-2ad7a80a-f191-4c81-a4e5-42c2e6276b88.png)

**Comment by NikGovorov** [comment]
What does `node -v` output?

**Comment by omerson-cruz** [comment]
this one 

![image](https://user-images.githubusercontent.com/65213312/228131701-2711da54-1342-4456-912e-829d6d0b8c7b.png)

**Comment by omerson-cruz** [comment]
Ooh I think it does not work on older version of Node? I tried switching to node v18.12.1 using nvm then it is working now. Awesomme!  :)

![image](https://user-images.githubusercontent.com/65213312/228132616-175a46b1-b466-4c2e-b113-a0de5264e965.png)


Btw is it possible to make it work on older version of node? or in what particular node is it compatible with?

**Comment by omerson-cruz** [comment]
I also tried it on v16.x.x of node and it's working. So I think it does not work with v14.x.x and below?? if I'm not mistaken.

**Comment by tuan-dd** [comment]
> @tuan-dd your issue is different from the original one. `node` doesn't run Typescript files by default, try `console-ninja npx tsx .\sample.
thank , it work when i run node index.js, but when run server it not working  
![image](https://user-images.githubusercontent.com/118432439/228134293-5a330f43-86f8-4d3b-bed7-b59b985eb13a.png)

**Comment by NikGovorov** [comment]
@omerson-cruz, 16.12.0 is the minimum version for the feature.

**Comment by NikGovorov** [comment]
@tuan-dd does it work if you rename `www` to `www.js`?

**Comment by tuan-dd** [comment]
> @tuan-dd does it work if you rename `www` to `www.js`?

Thank you very much. But I don't understand, when www name I run yarn start it works properly, but when using ninja console it doesn't work

**Comment by omerson-cruz** [comment]
@NikGovorov thanks for your clarification and support. All the best to the Wallaby team :)

I think we can now close the ticket?

**Comment by NikGovorov** [comment]
@tuan-dd, We've fixed the issue when the command fails on files with no extension in the latest extension version. However, Console Ninja won't show logs/errors in such files, the files must have an extension, so Console Ninja understands that it needs to process them. 

If you have more issues with Console Ninja, please create a new issue.

**Comment by Alecto** [comment]
Console Ninja is inactive
![image](https://github.com/wallabyjs/console-ninja/assets/8464662/876fe289-b74d-4eac-b033-97e9cb4d342c)

i use live server 
![image](https://github.com/wallabyjs/console-ninja/assets/8464662/cb97366f-0d79-47ea-b474-d6afc8bb3dcf)

and latest node
![image](https://github.com/wallabyjs/console-ninja/assets/8464662/2ac1b6cc-125e-49de-9975-9d15e2e32c92)

could you help me , please?

**Comment by smcenlly** [comment]
@Alecto - this issue is closed and unrelated; I've created a new issue on your behalf where we will respond to your request: #183.
