### ISSUE TITLE
[Bug]: npx calls inside npm run scripts return permission denied when Console Ninja is installed on WSL

### ISSUE THREAD

**Issue by evelynhathaway** [wallabyjs/console-ninja#122]
### What happened?

When I run an `npx` command inside a script defined inside my `package.json`, it returns the following.

```bash
$ npm test

> my-package@1.0.0 test
> npx jest

/usr/bin/env: ‘bash\r’: Permission denied
```

I tried what fixed this problem for other WSL users, and I found that didn't help. However, I noticed it never errored when I ran the same command in terminals other than VS Code terminal. I eventually narrowed it down to my recent upgrade to `wallabyjs.console-ninja@0.0.92`. Disabling Console Ninja and restarting VS Code prevents the error.

It seems to be specifically when `npx` command inside a npm run script since an `npx` command in the terminal works fine, and removing `npx` from the script also works.

### Version

v0.0.92

### Steps to reproduce (or sample repo)

1. Install Console Ninja
2. Open the integrated terminal in VS Code
3. Run a npm script with `npx jest`

### Log output

```shell
I cannot redact this large file and the logs don't include timestamps to make this easier on me. Nothing relevant appears near the tail. Add a comment if it cannot be reproduced and I will see what I can do.
```

**Comment by NikGovorov** [comment]
Thanks for providing the detailed set of steps to reproduce the problem. We were able to duplicate the problem and have released a new version of Console Ninja that fixes the problem (v0.0.94).
