### ISSUE TITLE
[Bug]: Code Ninja extension is not working with my Docker React app (Webpack)

### ISSUE THREAD

**Issue by nilssonj-tgc** [wallabyjs/console-ninja#125]
### What happened?

I was expecting Code Ninja to work with my Docker React app (Webpack-configured) but the extension says it's waiting for Webpack to start. Bug or faulty initial setup/configuration? Here's the output:

![image](https://user-images.githubusercontent.com/112423779/228934222-f5729e3f-7a38-44bd-8a86-d3a3f1be33b5.png)

### Version

v0.0.100

### Steps to reproduce (or sample repo)

- Added the list of allowed hosts within the extension settings
- Restarted VSCode
- Started Docker containers
- Once built, React app loads
- Start Code Ninja
- Displays message "Console Ninja is ⌛ waiting for webpack to start. Console Ninja has successfully integrated with webpack found in your project dependencies, but has not connected to a running instance of it yet."

### Log output

```shell
See screenshot.
```

**Comment by smcenlly** [comment]
Unfortunately your steps to reproduce are not detailed enough for us to fully understand what's going on.

You mentioned that you `Started Docker containers`. Did you use the `Dev Containers: Attach to Running Container...` command (`remote-containers.attachToRunningContainer`) to open Console Ninja within your container before loading react?

If you are starting a container and starting react in that container without first opening it in VS Code with Console Ninja running, then Console Ninja will not be enabled for your project.

**Comment by smcenlly** [comment]
@nilssonj-tgc - can you please provide the information requested?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Please provide the details requested and we will re-open the issue.
