### ISSUE TITLE
[Bug]: NextJS app no longer showing console logs

### ISSUE THREAD

**Issue by michaelaflores** [wallabyjs/console-ninja#129]
### What happened?

On a previous version from perhaps some weeks or more ago (can't say which as there are a number of releases), console logs showed up inline. Now no console logs show up in VS Code.

### Version

0.0.105

### Steps to reproduce (or sample repo)

Attempt to log in a NextJS app's components. 

### Log output

```shell
Permission denied with sudo
```

**Comment by ArtemGovorov** [comment]
We've tried Console Ninja on some sample next.js projects (including the latest next.js version) and it's working for us as expected:
<img width="782" alt="Screen Shot 2023-04-06 at 9 55 19 am" src="https://user-images.githubusercontent.com/979966/230238903-54939bf0-2268-41d2-b58a-5875b77fbf84.png">

Can you please: 
- provide the content of the `~/.console-ninja/trace.log` log file,
- share a sample repo where the issue can be reprodced.

**Comment by tuan-dd** [comment]
![image](https://user-images.githubusercontent.com/118432439/234011019-e7e4be59-c54a-4784-b45e-c700746145a8.png)
 i have issues console.log not show
