### ISSUE TITLE
Implement a watch on vite BUILD

### ISSUE THREAD

**Issue by carlosrziegler** [wallabyjs/console-ninja#13]
Hey, first i think this extension is amazing.

I have a case in that I link ( npm link )the package to my Application, in my APP the console ninja works fine, but not works on my Package. I think because NINJA waiting for server command of my Package ( using vite serve / start / dev ) BUT in my case I using a build command with watch flag to build if I change something . I this case NINJA not works :( 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/86771140/206511301-446c8092-a7ab-4584-a7f5-7384bebd9622.png">
 
 
 We can implement it to works in this case ?

**Comment by ArtemGovorov** [comment]
Can you please provide a sample of your project structure or a tree that we can re-create it from to reproduce? Please specify what folders contain the app and the package, as well what folder do you have opened in VS Code.

**Comment by smcenlly** [comment]
Closing this issue as we require more information and have not heard back. If you reply with the information requested, we will re-open this issue.
