### ISSUE TITLE
[Bug]: Yarn berry integration and antivirus

### ISSUE THREAD

**Issue by DSteinmann** [wallabyjs/console-ninja#131]
### What happened?

Hi, 
I was trying to clone and install https://github.com/storybookjs/storybook with the console-ninja plugin enabled in vscode. The initial installation failed and got flagged as ransomware by sophos, which locked my node installation for a while. 

Since the console-ninja binary was mentioned in one of the error messages, I tried to uninstall the extension in vscode it but the .yarnrc.yml file still has the plugin registered, which made yarn to fail on every command.

Maybe you could look into this

### Version

v0.0.106

### Steps to reproduce (or sample repo)

install Sophos Endpoint Security https://www.sophos.com/en-us/products/endpoint
clone https://github.com/storybookjs/storybook
run yarn task

### Log output

```shell
not existent anymore :(
```

**Comment by ArtemGovorov** [comment]
Closing this issue as we haven't heard back. If you reply with the information requested, we will re-open the issue.
