### ISSUE TITLE
[Bug]: "Notify about new features" checkbox does nothing

### ISSUE THREAD

**Issue by Tenrys** [wallabyjs/console-ninja#132]
### What happened?

![image](https://user-images.githubusercontent.com/3979239/232994746-3981feac-71b8-4c0b-9aba-b1ae2b4dee4e.png)

The checkbox is unticked, but I keep getting the "What's new" editor to show up when I don't want to see it.

### Version

v0.0.108

### Steps to reproduce (or sample repo)

I'm not sure what causes this.

### Log output

```shell
Log output was too long to post...
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in Console Ninja `v0.0.110`.
