### ISSUE TITLE
[Feature]: Expand/collapse in the free version

### ISSUE THREAD

**Issue by rolandleth** [wallabyjs/console-ninja#133]
Gating this rather basic functionality behind a paywall looks silly, at least from my point of view. Basic, not in its implementation (which might be very complex, I've no idea), but in what's expected of a feature that handles (large) JSON. I'll most likely end up purchasing the pro version anyway, so these are genuine thoughts and feedback, not a rant or complaint.

In any case, the extension is coming along really nicely, big props 💯

**Comment by smcenlly** [comment]
Thanks for taking the time to provide your feedback.

Our mindset to PRO features has been any functionality that we add that makes working in large / commercial projects easier **and** requires a fair bit of development effort to add / support. Our thinking is that these are features that should mostly only affect commercial users who would be willing to pay and helps us justify the effort to add them.

While it may not seem much at first glance, the way we're rending the formatted object with the read-only edit capability + copy/paste made adding this feature non-trivial. If you are working with large objects, you will probably also notice that with this change there's a bit improvement to overall performance of the log viewer as well.
