### ISSUE TITLE
[Bug]: Start command dissapeard

### ISSUE THREAD

**Issue by odi89** [wallabyjs/console-ninja#137]
### What happened?

It started a couple weeks ago suddenly when i started coding i lost the start command to console ninja. 
All the other commands are there but when i click one of them this message appears
"
command 'console-ninja.openStartView' not found
"

I solved the issue bye adding console.nina to path and install a previous version of the extension. 
But this week the same thing happened, i tried the soulution that worked before, but now it does not work.

I tried to remove the .console-ninja folder and reinstall, but when i do so it cant seem to find the .bin folder inside the .console-ninja directory the only thing there is a empty trace.log file 

Does anyone have workaround?
Sorry for litte context, but this is one of my fav extensions and i feel lost without it
Thanks for poiting me in the right directi
![Skjermbilde 2023-04-25 kl  10 25 39](https://user-images.githubusercontent.com/34927672/234219552-dd0638a6-32fe-4a0f-860b-ca1991819899.png)
on

### Version

v0.0.111

### Steps to reproduce (or sample repo)

Install latest version

### Log output

```shell
empty file
```

**Comment by ArtemGovorov** [comment]
Please try uninstalling the extension, then delete all `~/.vscode/extensions/wallabyjs.console-ninja-0.0.*` folders and install the extension again, it should help.

**Comment by odi89** [comment]
Hey @ArtemGovorov 🥺, thanks for replying to my issue!
I tried your solution.

Steps:
* Uninstall extension

* Delete  ~/.vscode/extensions/wallabyjs.console-ninja-0.0.*
* Reinstall extension in vscode

Still same issue. 
![Skjermbilde 2023-04-26 kl  16 19 40](https://user-images.githubusercontent.com/34927672/234605664-4a2fc0fc-d996-48bd-8355-ea47b3699a5d.png)

![Skjermbilde 2023-04-26 kl  16 18 27](https://user-images.githubusercontent.com/34927672/234605671-bdbdd2b8-2410-4dbd-a6d1-a4105c9b6d9f.png)


There is no .bin file in 
 ~/.console-ninja
 just a empty trace file. 
 Previously it has been a bin file in this directory 

Any further suggestions would be appreciated=)

Kind Regards
Seb

**Comment by smcenlly** [comment]
Can you please try the following.

1. Close all instances of VS Code
2. Run `rm -rf ~/.vscode/extensions/wallabyjs.console-ninja*`
3. Edit `~/.vscode/extensions/.obsolete` and remove any `console-ninja` entries that you see there
4. Edit `~/.vscode/extensions/extensions.json` and remove any `console-ninja` entries that you see there
5. Restart VS Code (it may prompt you that extensions have been modified and to reload).
6. Reinstall Console Ninja in the Extensions section of VS Code.

If it's still not working for you after trying that, please run the `Developer: Toggle Developer Tools` and share your console output. There may be some errors in your console output that will help us understand why it's not working for you.

**Comment by odi89** [comment]
@smcenlly 
Thank you for your help. When i toggeled on the developer console i found this!

<img width="578" alt="Skjermbilde 2023-04-28 kl  17 07 21" src="https://user-images.githubusercontent.com/34927672/235187670-ea892f9c-4b93-46a9-a450-8cf55d904934.png">

This helped me to track down a syntax error inn my settings.json file. 
When this was fixed console ninja worked like a charm again. 

Again thanks for helping me out, this issue can be closed now
🔥
