### ISSUE TITLE
Does not work with Shopify's Hydrogen Framework 

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#14]
Hi Wallaby team, 

Is there any chance that you guys will support Shopify Hydrogen Framework? seems like it does not work with Hydrogen as of the moment. Or I'm not sure if I needed to do something with the configuration of vite since Hydrogen uses vite which console-ninja already supported

**Comment by smcenlly** [comment]
We're not familiar with Shopify's Hydrogen framework, but we'll check it out and let you know.

**Comment by smcenlly** [comment]
We've added support for Spotify's Hydrogen Framwork in Console Ninja `v0.0.21`. Please update to the latest version, it should work for you.

**Comment by omerson-cruz** [comment]
Hi @smcenlly  , 

Thanks for your quick response. Btw I've just retested the Hydrogen Framework with the latest Console-Ninja as of the moment `(v.0.0.24)` and it's working 😃 . You guys are really super aweseme <3

Btw below is the SS of my latest testing of Console Ninja with Hydrogen Framework. And it's working 😃 . 

![image](https://user-images.githubusercontent.com/65213312/206762568-ce02b602-cc9d-4e80-a22d-b5bab69c9d31.png)

=============================================================

ALso I noticed that you guys marked Shopify Hydrogen as "Spotify" 😄  on the Extension description. 

![image](https://user-images.githubusercontent.com/65213312/206763121-2431166c-c921-48f8-a063-c089489b3b4c.png)
