### ISSUE TITLE
Console ninja causes problem with git

### ISSUE THREAD

**Issue by nonameolsson** [wallabyjs/console-ninja#144]
Type: <b>Bug</b>

I have console ninja activated, and the extension host crashes. 

Extension version: 0.0.120
VS Code version: Code - Insiders 1.79.0-insider (efb49cc271d6eea5634ac395e36e1e4cd108a447, 2023-05-10T05:51:32.996Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|32.00GB (1.86GB free)|
|Process Argv|--crash-reporter-id 9888d017-abdc-412c-bc0e-38a052d22f8e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30725951
azdwalk:30721579
pythonms35:30671666
f08j5886:30680471
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30724385
showsbindicator:30724477
pythongtdpath:30726887

```

</details>

**Comment by smcenlly** [comment]
Could you please:

1. Copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory.
2. Provide us with details of the error, specifically, what problems are you receiving and what makes you think it's Console Ninja? There doesn't appear to be any detail in your report that shows that.

**Comment by nonameolsson** [comment]
> Could you please:
> 
> 1. Copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory.
> 2. Provide us with details of the error, specifically, what problems are you receiving and what makes you think it's Console Ninja? There doesn't appear to be any detail in your report that shows that.

1. https://pastecode.io/s/f842d4u7
2. I used VS Code Extension Bisect, and it told me it was Console Ninja. After disabling it I have had a more stable VS Code.

**Comment by nonameolsson** [comment]
> We don't think the issue is related to Console Ninja. Can you please try reinstalling? If/when git crashes, can you please provide a screenshot of the error and your git logs from VS Code output window?

Sure, thanks for the feedback! I have re-installed it. If it happens again I will let you know :)

Thank you for a great extension!

**Comment by smcenlly** [comment]
We're going to close this issue for now. If you have the problem again, reply here and we will re-open the issue. Alternatively, you may create a new issue if you prefer.
