### ISSUE TITLE
[Feature]: Support esbuild

### ISSUE THREAD

**Issue by iamakulov** [wallabyjs/console-ninja#149]
### Describe the feature you'd like.

Would it be possible to support [the esbuild bundler](https://github.com/evanw/esbuild)?

(Console Ninja already supports Vite [which uses esbuild] and the Cypress esbuild runner (#95). I’m not sure how these are implemented, but if Console Ninja plugs into esbuild for them, perhaps it could plug into esbuild when it’s used directly?)

**Comment by smcenlly** [comment]
Can you please provide a sample repo that shows how `esbuild` integrates with running your development environment?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you reply with the information requested, we will re-open the issue.

**Comment by iamakulov** [comment]
Apologies for the delay! Sure, here’s an example repo: https://github.com/iamakulov/console-ninja-esbuild-demo

**Comment by smcenlly** [comment]
Thanks for the sample repo.

They way that you're building and running your code is incompatible with how Console Ninja works.

In your case, you have a two part build / serve process. You first compile your source code to the `build` folder, and then you `serve` from the built / compiled files.

Console Ninja needs to run on your project files in your editor, as you're modifying them. In your case, this process is disconnected and so Console Ninja does not know how your source files relate to your editor.

For your specific scenario, we recommend that you configure a tool such as [vite](https://vitejs.dev) to run `esbuild` and to serve your application in your dev environment. Once you have configured your files to be served with `vite`, Console Ninja should work for you with you needing to do anything else.
