### ISSUE TITLE
TypeError: Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by captain-rocket** [wallabyjs/console-ninja#15]

**Comment by smcenlly** [comment]
Could you please tell us a little about your project (what tech are you using), and would you mind providing a screenshot of this error to help us determine where it occurred?

**Comment by captain-rocket** [comment]
Simon,Vuejs 2.6.14Babel 7.14.2Webpack 5.46Typescript target es2020Node 14.16.1Core-js 3.12.1Eslint 7.31.0Yarn 1.22.9Roger BrownSent from my iPhoneOn Dec 8, 2022, at 7:34 PM, Simon McEnlly ***@***.***> wrote:﻿
Could you please tell us a little about your project (what tech are you using), and would you mind providing a screenshot of this error to help us determine where it occurred?

**Comment by ArtemGovorov** [comment]
@captain-rocket would you mind providing a screenshot of this error to help us determine where it occurred?

**Comment by captain-rocket** [comment]
MacOS 13.0.1VSCode 1.74.0Roger BrownSent from my iPhoneOn Dec 9, 2022, at 11:17 PM, Artem Govorov ***@***.***> wrote:﻿
@captain-rocket would you mind providing a screenshot of this error to help us determine where it occurred?

**Comment by smcenlly** [comment]
@captain-rocket - it looks like you tried to reply to the issue using your mail client but a screenshot didn't come through. You will need to log into the issue and attach the screenshot using your browser.

**Comment by captain-rocket** [comment]
It says at the bottom I could reply to the email directly. Just FYI. Roger BrownSent from my iPhoneOn Dec 12, 2022, at 6:58 PM, Simon McEnlly ***@***.***> wrote:﻿
@captain-rocket - it looks like you tried to reply to the issue using your mail client but a screenshot didn't come through. You will need to log into the issue and attach the screenshot using your browser.

**Comment by captain-rocket** [comment]
<img width="975" alt="EE90A451-7EFD-41FA-85F6-6F0AF363ADA8" src="https://user-images.githubusercontent.com/59418774/207186860-b3bcaef8-db05-459a-9f67-1849421791ed.png">

**Comment by captain-rocket** [comment]
The emails said you could reply directly. FYI

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. The issue should be now fixed in v0.0.35+.

**Comment by captain-rocket** [comment]
Awesome! loving this tool!
