### ISSUE TITLE
[Feature]: Babel implementation

### ISSUE THREAD

**Issue by Jonas22rr** [wallabyjs/console-ninja#150]
### Describe the feature you'd like.

Hi,

your tool is insane helpful :) 
but for me is babel compilation missing.

Can you add this please

Thank you for your nice Tool.

Regards Jonas :)

**Comment by smcenlly** [comment]
Can you please provide more details on your project? Console Ninja will use Babel if it is used by your development tooling and your development tooling is supported by Console Ninja.

Are you able to provide a sample project (or else links) to the same technology you use to run your development environment (e.g. `npm run dev`)?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you reply with the detail requested, we will reopen the issue.
