### ISSUE TITLE
[Feature]: Disable hoisting in build output

### ISSUE THREAD

**Issue by jsbrain** [wallabyjs/console-ninja#157]
### Describe the feature you'd like.

Building my Astro project I noticed that the console ninja script get's injected in the hoisted.js assets and included in my production build.

Not sure if that's intentional but I'd argue this should at least be an option to disable and probably not be included by default in a build. While my build probably will mostly happen in CI which will result in console ninja not being injected there, I find it a bit confusing that this is the default behaviour.

**Comment by smcenlly** [comment]
Thanks for using Console Ninja.

The behavior you describe is by design, and is how Console Ninja functions. This is fully described in [our docs](https://github.com/wallabyjs/console-ninja#how-does-it-work):

> Console Ninja integrates with locally installed tools that are building/preparing your code, and then inspects and adjusts your code (in a way that doesn't change how it executes) before it gets to the runtime (browser or node process that runs the code).
> 
> To integrate with supported tools seamlessly, Console Ninja patches your locally installed node modules. When you stop Console Ninja in the editor with the `Pause` command, all patches are removed.
> 
> Console Ninja detects if you are running your tool in production mode (by checking CLI flags and process environment variables). When production mode is detected, the tool will not modify your application code even if Console Ninja is running. In the (unlikely) case that you are running production builds on your local dev computer and are deploying or sharing local builds outside of your machine, we recommend running the Console Ninja `Pause` command in your editor prior to running your build to guarantee that no instrumented code ends up in your production code.
> 
> Console Ninja instrumentation is limited to sending runtime values for `console.log` and errors to your locally running editor only (`localhost` hosted websocket server). The runtime data from your app is **never** sent outside of your local machine. If the code of your application is somehow instrumented by Console Ninja and then used outside of your local machine for some reason:
> 
> - in browser, it will simply do nothing if the app host is not `127.0.0.1`, `localhost`, or one of your network adapter's IP v4 addresses. To connect from a different host name, use the `console-ninja.allowedHosts` VS Code setting.
> - in node, it will fail to connect to `localhost` and will not stop your app from working.

---

If you do **not** use your local development version for deploying your production system, this shouldn't cause a problem. As mentioned in the docs, you may use the `Pause` command to remove all patches if you do need to deploy from your local environment.

**Comment by ArtemGovorov** [comment]
> Console Ninja detects if you are running your tool in production mode (by checking CLI flags and process environment variables). 

In the recently released v1.0.155, we have added `astro build` flag check, so if you are using `astro build` command to build for prod locally, Console Ninja will not inject its instrumentation anymore.
