### ISSUE TITLE
Not working with Vite/React.

### ISSUE THREAD

**Issue by itsxScrubz** [wallabyjs/console-ninja#16]
Currently unable to get the extension working. Tried on both a current React / Vite project and a new barebones project...both with the same error.

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react.js?v=fe5f9519' does not provide an export named 'default' (at app.tsx:1:1)`

Trace log:

```
info host ------------ starting ------------
info host client connected: extension { address: '::', family: 'IPv6', port: 34071 }
info host starting host: {"extensionFolder":"/home/scrubz/.vscode/extensions/wallabyjs.console-ninja-0.0.18","runtimeHookFile":"/home/scrubz/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/scrubz/.vscode/extensions/wallabyjs.console-ninja-0.0.18/out/runtimeHook/errorHandler.js","filesToInstrument":["/home/scrubz/code/github/website/src/app.tsx"],"debug":false,"config":{"dateTimeFormat":"hh:mm:ss.SSS","openLinksInEditor":true,"maxLogViewerEntries":15000,"autoClearLogViewerOnFileChanges":true,"outputMode":"Beside File","toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve"]}}
info host starting tools discovery and integration
info host looking for tools to patch
info host worker Starting Host Worker...
info host found 1 tool file(s) to patch
info host patching /home/scrubz/code/github/website/node_modules/vite/bin/vite.js
info host completed tools discovery and integration
info buildHook-813806 installing build hook for vite at /home/scrubz/code/github/website
info buildHook-813806 allowed tools: vite, jest, webpack, next.js, cypress, http-server, serve
info buildHook-813806 running tools: vite
info host client connected: buildHook { address: '::', family: 'IPv6', port: 34071 }
info buildHook-813806 installing fs interceptor
info buildHook-813806 allowed tools: vite, jest, webpack, next.js, cypress, http-server, serve
info buildHook-813806 running tools: vite
info buildHook-813806 file processed (stat): 0 log points, error handler: true
info buildHook-813806 file processed (stat): 1 log points, error handler: false
info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 34071 }
info host client disconnected: buildHook 1006
info host client disconnected: buildHook 1006, has clients false
info host client disconnected: runtimeHook 1001
info host client disconnected: runtimeHook
```

Can provide the barebones project used to repro this issue along with the node_modules if needed.

**Comment by smcenlly** [comment]
FYI: https://create.t3.gg

**Comment by itsxScrubz** [comment]
> FYI: https://create.t3.gg

...?? I mean I know of it yes. Haven't played around with it yet tho. I'm not sure how that plays any part in this tho. Am I missing something??

**Comment by ArtemGovorov** [comment]
> Can provide the barebones project used to repro this issue along with the node_modules if needed.

Yes, please share the project. Fresh Vite + React generated app is our main dog-fooding/testing setup and is working for us.

**Comment by smcenlly** [comment]
Sorry - I had pasted in the wrong issue.

I've been trying to reproduce your issue but it's working for me.

I'm doing the following:

1. `npm create vite@latest`
2. Provide name of `my-vite-react`
3. Select `react`
4. Select `TypeScript`
5. `cd my-vite-react`
6. `npm install`
7. `code .` (open in VS Code)
8. Within VS Code terminal, run `npm run dev`
9. Add `console.log("Hello World");` to `App.tsx` 
10. Open URL (provided in from terminal) in browser

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/2074089/206598778-7a2ca7e5-8184-4a44-a34a-56627e86742d.png">

Could you please confirm if the steps provided above work for you?

**Comment by itsxScrubz** [comment]
I did everything you asked step by step, same error. I made a repo with the code from both attempts, including the tracelogs.

https://github.com/itsxScrubz/consoleninjarepro

Currently running Ubuntu 22.10. If you need anything else lmk.

**Comment by smcenlly** [comment]
Thanks. Your repo worked for me on Mac. Trying on Ubuntu now.

Could you also please let us know your node version? `node -v` from the CLI?

**Comment by itsxScrubz** [comment]
![image](https://user-images.githubusercontent.com/49043506/206606333-f8f54c03-7775-44a4-a390-a733ce50fdb8.png)

!!! Sanity checks ftw. It's the integrated vscode terminal. Runs fine with regular cli, but anything with the integrated terminal spits out that code above.

**Comment by itsxScrubz** [comment]
![image](https://user-images.githubusercontent.com/49043506/206607273-4c523816-18ef-4b35-898b-a4cf290da5ff.png)

Just incase.

**Comment by smcenlly** [comment]
I want to make sure I understand you correctly. Are you saying that if you start VS Code and then run your dev command from the command-line, then Console Ninja is working for you? But if you start from the VS Code integrated terminal, it does not work?

If that's true, if you pause Console Ninja and then use the integrated VS Code terminal, do you have the same problem? Perhaps there's something in the VS Code terminal that is running a different version of node, or has some path/environment variable differences that is causing your problem?

**Comment by dchamp16** [comment]
I was reading this thread because I have the same error @itsxScrubz has. Since I wanted to use the ninja console badly using vite, I retried to create a vite app and followed @smcenlly step by step, except I used react - javascript instead of typescript. I did all the step-by-step except the npm install. I think that's the reason why I am getting the same error with @itsxScrubz, and on my second attempt, the error is gone

**Comment by itsxScrubz** [comment]
@smcenlly You are correct. Terminal works, integrated vscode terminal does not.  
Given what @dchamp16 said, I restarted the pc a few times, and tried reinstalling the project included in my repo posted above a ton of times. I was able to get it to work with the integrated vscode terminal twice so far after ~15 mins of fucking with it. But it weirdly produced this side effect each time rofl.

![image](https://user-images.githubusercontent.com/49043506/206632747-ee79f3d6-19e3-4425-826d-65ca151868d0.png)

**Comment by smcenlly** [comment]
@itsxScrubz - do you get the same behavior when Console Ninja is paused on your application? I don't think there's anything special Console Ninja is doing that would cause a difference in behavior depending on where it's running.

**Comment by itsxScrubz** [comment]
@smcenlly I just spent like 30 mins playing with it...and I'm actually getting decent results now. What I've been doing is pausing the app, deleting the node modules and reinstalling, then unpausing it. I've done it roughly 2 dozen or so times now, and it only happened once. But I did do this for you:  

https://streamable.com/2v7rsb  

I'm legit having more issues with that video atm. And it doesn't matter where I start the app from (vscode / cli).  

paused  
https://i.imgur.com/PeHy2vL.png

unpaused  
https://i.imgur.com/HbKHQCC.png

**Comment by eddiee-s** [comment]
Not working on Ubuntu 22  as well, same app working in windows but not in ubuntu. On pause it  outputs following error "WebSocket connection to 'ws://127.0.0.1:41885/' failed: "  obviously watching wrong port because app is runing on http://localhost:5174/  
Without pause:
![without-pause](https://user-images.githubusercontent.com/80527934/206880643-78dda8f7-e193-4641-8fac-e7943cf9e3ae.png)
With pause:
![with-pause](https://user-images.githubusercontent.com/80527934/206880770-628578bb-c8f5-4822-876e-1ae7593cf0c6.png)

**Comment by smcenlly** [comment]
@itsxScrubz, @eddiee-s - Just checking, are you using Ubuntu as the OS on a bare-bones machine? Or are you running Ubuntu within Windows (e.g. WSL)? I am pretty sure we have some WSL / VS Code remote issues to iron out so that may explain some strange behavior.

Can you also please let us know what version of `node.js` you are using?

**Comment by dev-seahouse** [comment]
@smcenlly tried  both node 16-lts and node-18lts in wsl using ubuntu ,  vite@4.0. Both are not working with WebSocket connection to 'ws://127.0.0.1:41885/' failed error just like ^

**Comment by itsxScrubz** [comment]
@smcenlly This is actually lit. I just spun it up again, and it's not shifting the root div anymore like in the pics above. I've reinstalled ~6 times, along with pausing console ninja while in dev mode and then restarting it. :)

Either y'all fixed it, or gandalf lives inside my pc. Either way, pog.

**Comment by smcenlly** [comment]
> @smcenlly This is actually lit. I just spun it up again, and it's not shifting the root div anymore like in the pics above. I've reinstalled ~6 times, along with pausing console ninja while in dev mode and then restarting it. :)

Let us know if you run into any other problems.

**Comment by smcenlly** [comment]
We identified a couple of issues related to how our runtime code modifications were being intercepted, most specificially with later versions of `node` LTS. If anyone on this thread is still having problems, please create a new issue with details of your specific issue.
