### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Runwiththewolf93** [wallabyjs/console-ninja#162]
### What happened?

A couple of things are happening actually. I realize that your extension is still in early stages of development, but it is giving me memory leak issues when my react projects boot up. Also I'm getting websocket errors, which is supposedly due to the fact that this extension is working on the same port as my react server? I didn't care to debug the issues, the app obviously still isn't ready for the general public.

### Version

0.0.169

### Steps to reproduce (or sample repo)

Just start up any react project with this extension and you will get issues.

### Log output

```shell
400 bad request error as soon as server starts up.
```

**Comment by ArtemGovorov** [comment]
Sorry to hear you are having issues when running the extension. Despite the fact that the extension is only a few months old, we have tens of thousands users using the extension every day in their projects without any issue.  

> Just start up any react project with this extension and you will get issues.

Generated `create-react-app`, `vite` template, `next.js` template are all working for us. Can you please tell a bit more about your stack? What tools are using as webserver/build tool?

**Comment by ArtemGovorov** [comment]
Can you please also share your `~/.console-ninja/trace.log` file?
