### ISSUE TITLE
Not working with my react nor react native projects

### ISSUE THREAD

**Issue by kennyegun24** [wallabyjs/console-ninja#163]
### Describe the feature you'd like.

Hello, good day to you,

I just installed console ninja extension, I tried using it on some of my react projcts, but it kept telling that it cannot find any tool that it works with on my project. I even restarted my pc several times, but still noting. Same goes with my react natie/expo app too.

Here is a screenshot
![image](https://github.com/wallabyjs/console-ninja/assets/109461921/bdcb4ae9-698a-408d-a8c9-f507e404aa77)

**Comment by ArtemGovorov** [comment]
It looks like you are using multi-project workspace. In this case you will need to run a command to [select the active project](https://github.com/wallabyjs/console-ninja/issues/91#issuecomment-1491436271) for Console Ninja to integrate with: it is the `Select Multi-Root Workspace Project` command from VS Code command palette.

Once the project is selected, try restarting Console Ninja on the project via `Console Ninja Start` command and it should work for you.

> react native/expo app

Please note that react native projects are only supported by Console Ninja on web simulator at the moment: https://github.com/wallabyjs/console-ninja/issues/6

**Comment by kennyegun24** [comment]
Hello, thank you for the suggestion, but it still is not working. I even tried creating a new window with just one project, yet it still shows thesame thing

**Comment by ArtemGovorov** [comment]
@kennyegun24 Can you please copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory?

**Comment by kennyegun24** [comment]
Okay.... here it is

`01:54:16.995 info extension stopping host
01:54:32.089 info extension host process output: port:[61986]
01:54:31.313 info host ------------ starting ------------
01:54:32.354 info host worker Starting Host Worker...
01:54:32.089 info extension 
01:54:32.568 info host client connected: extension { address: '::', family: 'IPv6', port: 61986 }
01:54:34.549 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\auth\\login\\Login.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
01:54:35.359 info host starting tools discovery and integration
01:54:35.360 info host creating C:\Users\hp\.console-ninja\.bin
01:54:35.368 info host installing C:\Users\hp\.console-ninja\.bin\loader.js
01:54:35.372 info host installing C:\Users\hp\.console-ninja\.bin\console-ninja.ps1
01:54:35.539 info host installing C:\Users\hp\.console-ninja\.bin\console-ninja.cmd
01:54:35.541 info host installing PATH C:\Users\hp\.console-ninja\.bin
01:56:11.041 info host looking for tools to patch
01:56:11.077 info host removing cache folder: 2e5814ec2a05b19f49d3d76c1b2844a2
01:56:16.753 info host found 0 tool file(s) to patch
01:56:16.760 info host completed tools discovery and integration
02:23:58.321 info extension stopping host
02:24:01.808 info extension host process output: port:[61986]
02:24:01.297 info host ------------ starting ------------
02:24:01.808 info extension 
02:24:02.431 info host worker Starting Host Worker...
02:24:02.447 info host client connected: extension { address: '::', family: 'IPv6', port: 61986 }
02:24:04.232 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:24:04.319 info host starting tools discovery and integration
02:24:04.612 info host looking for tools to patch
02:24:08.641 info host found 0 tool file(s) to patch
02:24:08.649 info host completed tools discovery and integration
02:26:14.755 info extension stopping host
02:26:14.765 info host removing cache folder: 44b131c2b2e66899d2cf1baca4dc2e9d
02:26:14.775 info extension stopping host
02:26:15.388 info extension client disconnected: 1006 
02:26:15.673 info extension host process output: port:[62293]
02:26:15.673 info extension 
02:26:15.633 info host ------------ starting ------------
02:26:15.736 info host client connected: extension { address: '::', family: 'IPv6', port: 62293 }
02:26:16.086 info host worker Starting Host Worker...
02:26:17.709 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\otherUserSlice.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\post_details\\PostDetails.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\other_user_profile\\OtherUserProfile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\currentuser_profile\\Profile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\feeds\\Homepage.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\likes\\Likes.jsx","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:26:17.774 info host starting tools discovery and integration
02:26:17.796 info host looking for tools to patch
02:26:29.538 info extension stopping host
02:26:38.999 info extension stopping host
02:26:39.988 info host found 0 tool file(s) to patch
02:26:40.002 info extension stopping host
02:26:39.990 info host completed tools discovery and integration
02:26:40.034 info extension stopping host
02:26:41.312 info extension host process output: port:[62298]
02:26:41.312 info extension 
02:26:41.193 info host ------------ starting ------------
02:26:41.392 info host client connected: extension { address: '::', family: 'IPv6', port: 62298 }
02:26:41.463 info extension host process output: port:[62298]
02:26:41.463 info extension 
02:26:41.240 info host ------------ starting ------------
02:26:41.493 ERR! host uncaught exception: listen EADDRINUSE: address already in use :::62298
02:26:41.575 info host client connected: extension { address: '::', family: 'IPv6', port: 62298 }
02:26:41.941 info host worker Starting Host Worker...
02:26:42.080 info extension client disconnected: 1006 
02:26:42.124 info host worker Starting Host Worker...
02:26:43.497 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\script.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\index.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\redux\\apiCalls.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\components\\PostsDetails.jsx","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:26:43.563 info host starting tools discovery and integration
02:26:43.581 info host looking for tools to patch
02:26:51.011 info extension stopping host
02:26:57.794 info extension stopping host
02:27:10.505 info extension stopping host
02:27:31.267 info extension stopping host
02:27:41.441 info host removing cache folder: a397014b551b36103bd9d357e6306cd1
02:28:01.201 info extension stopping host
02:28:01.210 info host removing cache folder: 880dadb260c76947d4aa003c0846a3a6
02:28:41.448 info host removing cache folder: 2baa8609dc2dc7cd3d0b789614eec424
02:29:14.793 info host starting tools discovery and integration
02:29:15.506 info host starting tools discovery and integration
02:29:25.333 info host found 4 tool file(s) to patch
02:29:25.398 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\index.js
02:29:25.399 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\webpack.js
02:29:25.426 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest\bin\jest.js
02:29:25.426 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest-runner\build\testWorker.js
02:29:25.585 info host looking for tools to patch
02:29:25.585 info host looking for tools to patch
02:29:25.585 info host completed tools discovery and integration
02:29:26.111 info extension client disconnected: 1006 
02:29:26.112 info extension client disconnected: 1006 
02:31:09.272 info extension stopping host
02:31:10.521 info extension host process output: port:[62293]
02:31:10.521 info extension 
02:31:10.331 info host ------------ starting ------------
02:31:10.717 info host client connected: extension { address: '::', family: 'IPv6', port: 62293 }
02:31:11.303 info host worker Starting Host Worker...
02:31:11.627 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\otherUserSlice.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\post_details\\PostDetails.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\other_user_profile\\OtherUserProfile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\currentuser_profile\\Profile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\feeds\\Homepage.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\likes\\Likes.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:31:11.664 info host starting tools discovery and integration
02:31:11.683 info host looking for tools to patch
02:31:13.622 info host found 1 tool file(s) to patch
02:31:13.625 info host patching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:31:13.746 info host completed tools discovery and integration
02:31:32.661 info extension stopping host
02:32:47.767 info extension stopping host
02:32:49.779 info extension host process output: port:[62293]
02:32:49.667 info host ------------ starting ------------
02:32:49.779 info extension 
02:32:49.749 info host removing cache folder: fa97eb49caf92741548906d20fd720fd
02:32:49.859 info host client connected: extension { address: '::', family: 'IPv6', port: 62293 }
02:32:50.331 info host worker Starting Host Worker...
02:32:50.720 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\otherUserSlice.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\post_details\\PostDetails.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\other_user_profile\\OtherUserProfile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\feeds\\Homepage.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\currentuser_profile\\Profile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\likes\\Likes.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:32:50.763 info host starting tools discovery and integration
02:32:50.807 info host looking for tools to patch
02:32:53.811 info host found 1 tool file(s) to patch
02:32:53.821 info host patching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:32:53.843 info host completed tools discovery and integration
02:33:00.503 info extension stopping host
02:33:02.572 info extension client disconnected: 1006 
02:33:06.077 info extension host process output: port:[62293]
02:33:05.477 info host ------------ starting ------------
02:33:06.077 info extension 
02:33:06.357 info host client connected: extension { address: '::', family: 'IPv6', port: 62293 }
02:33:06.652 info host worker Starting Host Worker...
02:33:08.107 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\otherUserSlice.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\post_details\\PostDetails.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\other_user_profile\\OtherUserProfile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\feeds\\Homepage.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\pages\\currentuser_profile\\Profile.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\likes\\Likes.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:33:08.142 info host starting tools discovery and integration
02:33:08.159 info host looking for tools to patch
02:33:59.380 info host found 1 tool file(s) to patch
02:33:59.383 info host patching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:33:59.405 info host removing cache folder: aa31996e9685fa58809ad1299d7a769e
02:33:59.411 info host completed tools discovery and integration
02:34:01.008 info extension stopping host
02:34:01.021 info host unpatching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:34:01.678 info extension client disconnected: 1006 
02:34:09.695 info extension stopping host
02:34:10.691 info extension host process output: port:[62298]
02:34:10.538 info host ------------ starting ------------
02:34:10.606 info host removing cache folder: 2326b7c117277eef96b5174a5feebbcb
02:34:10.691 info extension 
02:34:10.766 info host client connected: extension { address: '::', family: 'IPv6', port: 62298 }
02:34:11.151 info host worker Starting Host Worker...
02:34:12.728 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\redux\\apiCalls.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\index.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\components\\PostsDetails.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\src\\components\\homeComps\\PostCard.jsx","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\main.js","reason":"search"},{"path":"C:\\Users\\hp\\Desktop\\innovate_frontend\\script.js","reason":"search"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:34:12.763 info host starting tools discovery and integration
02:34:12.782 info host looking for tools to patch
02:34:45.279 info extension stopping host
02:35:19.549 info extension stopping host
02:35:19.557 info host removing cache folder: 3b631b7c44060c9001e20d1ddaaeb978
02:35:43.141 info host found 5 tool file(s) to patch
02:35:43.145 info host patching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:35:43.149 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\index.js
02:35:43.149 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\webpack.js
02:35:43.152 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest\bin\jest.js
02:35:43.152 info host patching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest-runner\build\testWorker.js
02:35:43.301 info host completed tools discovery and integration
02:35:43.318 info extension stopping host
02:35:43.304 info host unpatching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:35:43.306 info host unpatching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\index.js
02:35:43.307 info host unpatching C:\Users\hp\Desktop\innovate_frontend\node_modules\webpack\lib\webpack.js
02:35:43.309 info host unpatching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest\bin\jest.js
02:35:43.310 info host unpatching C:\Users\hp\Desktop\innovate_frontend\node_modules\jest-runner\build\testWorker.js
02:35:43.462 info extension stopping host
02:35:44.503 info extension host process output: port:[62430]
02:35:44.452 info host ------------ starting ------------
02:35:44.503 info extension 
02:35:44.630 info extension host process output: port:[62430]
02:35:44.474 info host ------------ starting ------------
02:35:44.645 ERR! host uncaught exception: listen EADDRINUSE: address already in use :::62430
02:35:44.630 info extension 
02:35:44.709 info host client connected: extension { address: '::', family: 'IPv6', port: 62430 }
02:35:44.713 info host client connected: extension { address: '::', family: 'IPv6', port: 62430 }
02:35:45.135 info host worker Starting Host Worker...
02:35:45.149 info host worker Starting Host Worker...
02:35:45.209 info extension client disconnected: 1006 
02:35:45.759 info host starting host: {"extensionFolder":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170","runtimeHookFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\hp\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.170\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\requestMethods.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\redux\\apiCalls.js","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\innovate_mobile\\src\\components\\feeds\\feedHeader.jsx","reason":"open"},{"path":"c:\\Users\\hp\\Desktop\\projects\\university_assignments\\main.js","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","BELINDA","192.168.137.1","192.168.182.234"],"host":"127.0.0.1"}
02:35:45.821 info host starting tools discovery and integration
02:35:45.838 info host looking for tools to patch
02:35:45.891 info host found 1 tool file(s) to patch
02:35:45.894 info host patching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:35:45.977 info host completed tools discovery and integration
02:36:36.840 info extension stopping host
02:36:36.856 info host unpatching c:\Users\hp\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
02:36:37.454 info extension client disconnected: 1006 
02:36:37.456 info extension client disconnected: 1006 
02:36:44.585 info host removing cache folder: 1f6a667245886aeed388174324aa5bfe
02:36:44.587 info host removing cache folder: 390089d5cbd1c4bb6b8d1b20132e40d3
`

**Comment by ArtemGovorov** [comment]
Thanks, it looks from the log that when you have `c:\\Users\\hp\\Desktop\\innovate_mobile` project opened in a separate VS Code window, the status of Console Ninja wasn't `inactive` like on your first screenshot, but was waiting for your build tools to start (`npm run start`).

Can you please close all VS Code instances, open `c:\\Users\\hp\\Desktop\\innovate_mobile` project in a separate VS Code window and check the status? It should NOT be `inactive`. Once you see that it's not, start/restart your `npm run start` command and check the status (share a screenshot of it if you are not sure what it means).

**Comment by kennyegun24** [comment]
Okay, thanks, I will try that out now

**Comment by smcenlly** [comment]
@kennyegun24 - it looks like you're using a mobile / react-native application. Is that correct?

As @ArtemGovorov said [above](https://github.com/wallabyjs/console-ninja/issues/163#issuecomment-1614051805):

> Please note that react native projects are only supported by Console Ninja on web simulator at the moment: https://github.com/wallabyjs/console-ninja/issues/6

**Comment by ArtemGovorov** [comment]
Closing this issue as we haven't heard back. If you reply with the information requested, we will re-open the issue.
