### ISSUE TITLE
[Bug]: Console Ninja logging mixed in Webpack project bundling

### ISSUE THREAD

**Issue by VladRafli** [wallabyjs/console-ninja#166]
### What happened?

I'm new on using Console Ninja, and I building production code for my [NestJS](https://docs.nestjs.com/) application. When there is a log from my app, the log returns this

`Console Ninja failed to send logs, restarting the process may help; also see https://tinyurl.com/37x8b79t:  to connect to host: failed to find and load WebSocket`

`logger failed to connect to host, see https://tinyurl.com/37x8b79t`

My NestJS build is bundled using webpack as the build result says. I don't know how Console Ninja logging inserted into my project build as it should be only an extension for vscode. Maybe is an edge cases that no one didn't aware of.

This is some of the screenshots of my application error log when it had an error

![image](https://github.com/wallabyjs/console-ninja/assets/29350923/3c3e8366-3ca1-4d00-9eac-68a0f24f467c)
![image](https://github.com/wallabyjs/console-ninja/assets/29350923/deac9fa4-cf8b-4cb0-963b-46aee8ff497f)

### Version

v0.0.174

### Steps to reproduce (or sample repo)

My project is for my thesis and therefore cannot be publicly available at the moment. But at least maybe we can reproduce it by creating new NestJS project

1. Initialize new NestJS project, [link to documentation here](https://docs.nestjs.com/)
2. Write some code that throws error (maybe like `throw new Error('Some error!')`
3. Build the project
4. Run the compiled project from dist folder
5. See console after running on endpoint that thrown error exception

### Log output

```shell
21:19:05.841 info host ------------ starting ------------
21:19:05.891 info extension 
21:19:05.934 info host client connected: extension { address: '::', family: 'IPv6', port: 52638 }
21:19:06.334 info host worker Starting Host Worker...
21:19:07.062 info host starting host: {"extensionFolder":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174","runtimeHookFile":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\scripts\\insertStatistics.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\jobs\\index.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\apps\\animal-adoption-nestjs\\src\\main.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\apps\\animal-adoption-nestjs\\src\\transactions\\transactions.service.ts","autoLogPoints":[{"range":{"startLine":89,"endLine":89,"startColumn":0,"endColumn":0}}],"reason":"autoLogPoints"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","DESKTOP-P44T8FS","192.168.119.1","192.168.56.1","192.168.1.5"],"host":"127.0.0.1"}
21:19:07.093 info host starting tools discovery and integration
21:19:07.126 info host updating C:\Users\Rafli\.console-ninja\.bin\loader.js
21:19:07.173 info host looking for tools to patch
21:19:25.237 info host found 4 tool file(s) to patch
21:19:25.241 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\webpack\lib\index.js
21:19:25.242 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\webpack\lib\webpack.js
21:19:25.259 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\jest\bin\jest.js
21:19:25.260 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\jest-runner\build\testWorker.js
21:19:25.368 info host completed tools discovery and integration
21:19:47.099 info extension stopping host
21:19:47.255 info extension client disconnected: 1006 
21:25:48.731 info extension stopping host
21:25:49.273 info extension host process output: port:[52638]
21:25:49.230 info host ------------ starting ------------
21:25:49.259 info host removing cache folder: f6c4cac8d1d4df4b30df751790a046c2
21:25:49.274 info extension 
21:25:49.305 info host client connected: extension { address: '::', family: 'IPv6', port: 52638 }
21:25:49.497 info host worker Starting Host Worker...
21:25:49.577 info host starting host: {"extensionFolder":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174","runtimeHookFile":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\Rafli\\.vscode\\extensions\\wallabyjs.console-ninja-0.0.174\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\scripts\\insertStatistics.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\jobs\\index.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\apps\\animal-adoption-nestjs\\src\\main.ts","reason":"search"},{"path":"E:\\Work\\Coding\\Website\\animal-adoption-nestjs\\apps\\animal-adoption-nestjs\\src\\transactions\\transactions.service.ts","autoLogPoints":[{"range":{"startLine":89,"endLine":89,"startColumn":0,"endColumn":0}}],"reason":"autoLogPoints"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","DESKTOP-P44T8FS","192.168.119.1","192.168.56.1","192.168.1.5"],"host":"127.0.0.1"}
21:25:49.599 info host starting tools discovery and integration
21:25:49.609 info host looking for tools to patch
21:25:50.082 info host found 4 tool file(s) to patch
21:25:50.084 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\webpack\lib\index.js
21:25:50.085 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\webpack\lib\webpack.js
21:25:50.086 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\jest\bin\jest.js
21:25:50.086 info host patching E:\Work\Coding\Website\animal-adoption-nestjs\node_modules\jest-runner\build\testWorker.js
21:25:50.088 info host completed tools discovery and integration
21:26:15.425 info extension stopping host
```

**Comment by smcenlly** [comment]
As mentioned in [our docs](https://github.com/wallabyjs/console-ninja#how-does-it-work):

> To integrate with supported tools seamlessly, Console Ninja patches your locally installed node modules.
> ...
> Console Ninja detects if you are running your tool in production mode (by checking CLI flags and process environment variables). When production mode is detected, the tool will not modify your application code even if Console Ninja is running. In the (unlikely) case that you are running production builds on your local dev computer and are deploying or sharing local builds outside of your machine, we recommend running the Console Ninja Pause command in your editor prior to running your build to guarantee that no instrumented code ends up in your production code.

So the behavior that you're seeing is expected at times, depending on your CLI tools.

As per the text above, **we recommend running the Console Ninja Pause command in your editor prior to running your build to guarantee that no instrumented code ends up in your production code**.

We created a `next.js` project and didn't have the same problem, so we suspect that your CLI flags or package versions may be different for your project, which is why we're not detecting your production mode build. We'd appreciate if you could share your project with us, or else a sample that has the same problem so we can explicitly disable Console Ninja in this case.

**Comment by smcenlly** [comment]
@VladRafli - sorry, I misread your `Nest` as `Next.js`. I can see Console Ninja is being included in Nest production builds. We will investigate whether we can stop this from happening.

**Comment by smcenlly** [comment]
We've stopped Console Ninja from being injected in default `Nest` project builds in Console Ninja `v1.0.175+`. Having said that, we still **strongly recommend** running the Console Ninja Pause command in your editor prior to running your build on your local machine.

**Comment by VladRafli** [comment]
@smcenlly Thank you for your reply. 

I haven't read all the documentation as I'm experimenting with this extension, I hope there is a highlighted warning on the documentation if we want to build a project when Console Ninja is attached into our project so people could take note on this recomendation.
