### ISSUE TITLE
[Feature]: vite-node support

### ISSUE THREAD

**Issue by FractalHQ** [wallabyjs/console-ninja#171]
### Describe the feature you'd like.

[`vitest`](https://github.com/vitest-dev/vitest/tree/main) and [`vite-node`](https://www.npmjs.com/package/vite-node) respectively are great tools for running ts directly with module resolution and [what not](https://github.com/vitest-dev/vitest/tree/main/packages/vite-node#readme).  They'd make a great addition!

**Comment by smcenlly** [comment]
Thanks for your feature request.

Console Ninja already fully supports `vitest` and `vite-node` when launching as a [universal node application](https://github.com/wallabyjs/console-ninja#universal-node-applications).

For example, to run Console Ninja with vitest, you would use:

```bash
console-ninja npx vitest
```

And to run Console Ninja with `vite-node`, you would use:

```bash
console-ninja npx vite-node <filename>
```
