### ISSUE TITLE
Where can I find privacy policy of console ninja?

### ISSUE THREAD

**Issue by VictorGin** [wallabyjs/console-ninja#176]
### Issue description or question

I'm working in projects where my code bases are confidencial. I need to know if Console ninja keeps a copy of my code or something like that or not?

**Comment by smcenlly** [comment]
This question is addressed in [our docs](https://github.com/wallabyjs/console-ninja#how-does-it-work):

> The runtime data from your app is **never** sent outside of your local machine.

---

It is safe to use Console Ninja on private / confidential code bases. Everything is processed locally and we never have access to any of your code.
