### ISSUE TITLE
[Feature]: Support http and https node module

### ISSUE THREAD

**Issue by demosofa** [wallabyjs/console-ninja#177]
### Describe the feature you'd like.

Why this wasn't implemented from the start if many nodejs framework like expressjs, koa and fastifyjs use these modules.

**Comment by smcenlly** [comment]
Can you please include a sample project that shows your usage scenario?

Console Ninja does support [Universal Node Applications](https://github.com/wallabyjs/console-ninja#universal-node-applications), so if you're looking to capture your server-runtime code, that should work for you.

If you're serving file(s) over `http` / `https`, then Console Ninja would need to better understand your application entry point. We can determine this for various UI frameworks and bundling tools, but if you are serving raw HTML over `http` or `https` modules then this may not be supported right now.

Once we understand your usage scenario, we should be able to better advise a solution, or consider your feature request.

**Comment by smcenlly** [comment]
Closing this request as we require additional detail and have not heard back.
