### ISSUE TITLE
[Feature]: Change comment color

### ISSUE THREAD

**Issue by sanishkarkee** [wallabyjs/console-ninja#179]
### Describe the feature you'd like.

my editor comment color and console ninja comment  comment color is same and its creates a bit confusion. Is there any way to change console ninja's comment color?

**Comment by ArtemGovorov** [comment]
Yes, Console Ninja VS Code settings allow to change the colors:


<img width="1050" alt="Screen Shot 2023-08-03 at 9 05 09 am" src="https://github.com/wallabyjs/console-ninja/assets/979966/15dc49ff-1761-44fe-bd81-2b92ae04fa59">

**Comment by sanishkarkee** [comment]
Thank you Artem :)
