### ISSUE TITLE
[Feature]: Specify static port

### ISSUE THREAD

**Issue by ViewableGravy** [wallabyjs/console-ninja#180]
### VSCode Setting to specify the port that console ninja uses

I typically work on my projects using VSCode Remote Server, this has the great feature of allowing ports to be forwarded to localhost, however, since the port used for console ninja, looks to be a range, this will change each time I compile and run my application.

Having a setting to specify a static port for this to listen on should solve this problem.

**Comment by ArtemGovorov** [comment]
Last time we have tested, Console Ninja worked with VSCode Remote Server, with correct automatic port forwarding. Can you please provide some more details about what exactly is not working for you (ie. share some screenshots/error messages)?

**Comment by ViewableGravy** [comment]
Thanks for getting back!

I am running React 18 using create-react-app. I run this with the following command (as a yarn script):
`PORT=3006 react-scripts start`

This correctly opens port 3006, no issues.

I also normally run an Express Application on the same remote server which runs on port 3002. 

When I do start the application, I get a number of errors in the console for connections of a websocket on a random port.
![image](https://github.com/wallabyjs/console-ninja/assets/42259073/302ca6a1-c81b-478f-b425-df508d379f69)

If I then manually forward the port, it works.

Just to be sure, I've tried all three "Auto forward ports source" modes and have ensured that Auto Forward Ports is enabled:
![image](https://github.com/wallabyjs/console-ninja/assets/42259073/79507de3-b875-4f65-8d99-6dc5f9446988)

Clearly, given that it is trying to make the connection, the extension is running and trying to connect to something, it's just not able to make the connections. 

I am connecting from a Windows 11 desktop to an Ubuntu 20.04.6 LTS linux machine.

Appreciate the help or if there is anything else I can provide, let me know

**Comment by smcenlly** [comment]
Thanks for providing the additional detail. There was a problem running with SSH remote workspaces and we needed to update Console Ninja to automatically forward the port it uses at runtime.

Please update to the latest version of Console Ninja, `v0.0.190`, it will fix your problem.
