### ISSUE TITLE
[Feature]: Support for vue js

### ISSUE THREAD

**Issue by vkdeveloper07** [wallabyjs/console-ninja#181]
### Describe the feature you'd like.

Its awesome extension . bit I found that is not supporting .vue files. Any plan to add support for .Vue components?

**Comment by ArtemGovorov** [comment]
Console Ninja fully supports `.vue` files. Can you please share a sample project where it's not working for you? We are happy to take a look and investigate.

**Comment by vkdeveloper07** [comment]
Actually I created new Vue project and tried it and it worked. But I have another project in which I am trying to use this extension, but putting console.log() is not displaying data. please find below screen shot
![code](https://github.com/wallabyjs/console-ninja/assets/52969107/3002ddb5-9d9d-41a0-8a69-9e8d8e2fd9a6)

**Comment by smcenlly** [comment]
@vkdeveloper07 - Can you please provide us with:

1. Steps to reproduce your issue or else a sample repo that has your problem
2. Your log output from the `~/.console-ninja/trace.log` **after** you have tried in the project and confirmed it's not working.

**Comment by smcenlly** [comment]
Thanks for the sample repo. We've been able to reproduce the problem.

We'll investigate early next week and provide an update at that time.

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo. We have fixed the problem and released the fix in v0.0.192+ of the extension.

**Comment by vkdeveloper07** [comment]
Thank you . I will check the same
