### ISSUE TITLE
[Feature]: Show the path breadcrumb of the currently highlighted json

### ISSUE THREAD

**Issue by venkatd** [wallabyjs/console-ninja#186]
### Describe the feature you'd like.

Currently when I log out a very large json file, I need to know where exactly I am.

<img width="739" alt="CleanShot 2023-08-09 at 13 08 38@2x" src="https://github.com/wallabyjs/console-ninja/assets/220686/2f13ab26-f6c4-423b-a159-b738b4ad65a6">

It would be great to orient myself by showing me the breadcrumb of what is currently selected.

Can take inspiration from how vscode shows this for code:
<img width="737" alt="CleanShot 2023-08-09 at 13 09 58@2x" src="https://github.com/wallabyjs/console-ninja/assets/220686/d876e080-828d-4e7e-9ca3-ca220685f7bf">

**Comment by ArtemGovorov** [comment]
Thanks for creating the feature request. The breadcrumb control has been added and just released in v0.0.199+ of the extension:

![breadcrumbs](https://github.com/wallabyjs/console-ninja/assets/979966/20c8fc17-6fec-4211-93e5-fd8f50f1f7ce)

**Comment by venkatd** [comment]
Wow that was fast. Amazing!

**Comment by omerson-cruz** [comment]
This is a great feature. Team wallaby did it again <3
