### ISSUE TITLE
[Bug]: Current status      Console Ninja is  inactive. Console Ninja has scanned your project dependencies, but has not found any tools that are supported.

### ISSUE THREAD

**Issue by JieeWu** [wallabyjs/console-ninja#187]
### What happened?

Operating System: macOS
Nextjs

<img width="572" alt="截圖 2023-08-10 下午1 02 09" src="https://github.com/wallabyjs/console-ninja/assets/45639267/970ce146-d951-4b31-8888-0ea8b7eee6f1">

<img width="1470" alt="截圖 2023-08-10 下午1 01 39" src="https://github.com/wallabyjs/console-ninja/assets/45639267/929e9204-70b9-437e-b7b2-78c2df79e153">

### Version

v0.0.195

### Steps to reproduce (or sample repo)

I installed Console Ninja from VS Code, but I can't use console-ninja in the terminal, and I've been consistently unable to locate dependencies. I kindly request the team's assistance in resolving this issue.

### Log output

```shell
12:59:30.533 info extension stopping host
12:59:30.539 info host removing cache folder: babc3f87c2b1ee891b5ed8fe7833430a
12:59:30.543 info host unpatching /Users/wujiajie/.vscode/extensions/ritwickdey.liveserver-5.7.9/node_modules/live-server/index.js
12:59:30.543 info host unpatching /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js
12:59:30.543 info host unpatching /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
12:59:30.543 WARN host could not get write access to /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js file
12:59:30.544 WARN host could not get write access to /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js file
12:59:30.658 ERR! host could not undo the patch because of the following error: next.js: Error: EPERM: operation not permitted, chmod '/users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js';Error: EPERM: operation not permitted, chmod '/users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js'
12:59:31.174 info extension client disconnected: 1006 
12:59:35.187 info extension stopping host
12:59:35.369 info extension host process output: port:[50898]
12:59:35.363 info host ------------ starting ------------
12:59:35.369 info extension 
12:59:35.376 info host client connected: extension { address: '::', family: 'IPv6', port: 50898 }
12:59:35.391 info host starting host: {"extensionFolder":"/Users/wujiajie/.vscode/extensions/wallabyjs.console-ninja-0.0.195","runtimeHookFile":"/Users/wujiajie/.vscode/extensions/wallabyjs.console-ninja-0.0.195/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/Users/wujiajie/.vscode/extensions/wallabyjs.console-ninja-0.0.195/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/forum/counter.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/posts/[id].js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/forum/checkbox.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/forum/reply/[post_id].js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/cart/orderdate.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/date/index.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/forum/post/[post_id].js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/pages/forum/post/post.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/member/login.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/header.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/ckeditor-button.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/api.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/search-post.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/forum-post-right.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/ckeditor.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/forum_post.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/category.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/forum-reply-content.js","reason":"search"},{"path":"/users/wujiajie/documents/code/reactandnode/next-base-main/components/forum/avatar-data.js","reason":"search"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/pages/forum/index.js","reason":"open"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/next.config.js","reason":"open"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/components/forum/category.js","reason":"open"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/pages/forum/reply/[post_id].js","reason":"open"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/components/forum/forum_post.js","reason":"open"},{"path":"/Users/wujiajie/Documents/Code/reactAndNode/next-base-main/pages/forum/post/[post_id].js","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"Beside File","captureFunctions":true,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":false,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","wujiajiedeMacBook-Air.local","192.168.0.102"],"host":"127.0.0.1"}
12:59:35.400 info host starting tools discovery and integration
12:59:35.403 info host looking for tools to patch
12:59:35.457 info host worker Starting Host Worker...
12:59:35.624 info host found 3 tool file(s) to patch
12:59:35.625 info host patching /Users/wujiajie/.vscode/extensions/ritwickdey.liveserver-5.7.9/node_modules/live-server/index.js
12:59:35.625 info host patching /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js
12:59:35.625 info host patching /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
12:59:35.625 WARN host could not get write access to /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js file
12:59:35.625 WARN host could not get write access to /users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js file
12:59:35.677 ERR! host failed to apply build hook related patches: Error: next.js: Error: EPERM: operation not permitted, chmod '/users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/compiled/webpack/bundle5.js';Error: EPERM: operation not permitted, chmod '/users/wujiajie/documents/code/reactandnode/next-base-main/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js'; 
12:59:35.678 info host completed tools discovery and integration
```

**Comment by JieeWu** [comment]
Thank you so much, the issue has been resolved. I apologize for the inconvenience. 😍

**Comment by Rafa2908** [comment]
My Console Ninja is inactive. I tried everything and nothing is working.

11:44:53.434 info extension stopping host
11:44:53.450 info host removing cache folder: b3c6865f22b3abd819e1e4bb8aceb0c2
11:44:53.461 info extension client disconnected: 1006 
11:44:53.462 info buildHook-11156 client disconnected: 1006 
11:44:53.463 info buildHook-11156 disconnected from host: 55908
11:44:53.463 info buildHook-11156 disconnected from all hosts
11:44:53.780 info extension host process output: port:[55908]
11:44:53.752 info host ------------ starting ------------
11:44:53.780 info extension 
11:44:53.793 info host client connected: extension { address: '::', family: 'IPv6', port: 55908 }
11:44:53.891 info host starting host: {"extensionFolder":"c:\\Users\\Jose Rafael\\.vscode\\extensions\\wallabyjs.console-ninja-1.0.276","runtimeHookFile":"c:\\Users\\Jose Rafael\\.vscode\\extensions\\wallabyjs.console-ninja-1.0.276\\out\\runtimeHook\\tracer.js","globalErrorHandlerFile":"c:\\Users\\Jose Rafael\\.vscode\\extensions\\wallabyjs.console-ninja-1.0.276\\out\\runtimeHook\\errorHandler.js","filesToInstrument":[{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\room1.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\roll.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\practica.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\loop.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\fizzbuzz.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\dojo pizzeria\\dojo-pizzeria.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\css-library\\css-library.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_conditionals.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_jspredict.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_looparray.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_loopdloop.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_mintofront.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_parameters.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_popfront.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_predict_output.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\code.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\fibonacci.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\practica1.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\practica2.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\rock_paper_game.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\practice.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_operators.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\coding-dojo-js\\coding dojo exercises\\calderon_jose_debug.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\array challenges\\better-than-average.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\array challenges\\fibonacci.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\array challenges\\high-pass-filter.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\array challenges\\array-reverse.js","reason":"search"},{"path":"c:\\users\\jose rafael\\desktop\\coding dojo\\array challenges\\always-hungry.js","reason":"search"},{"path":"c:\\Users\\Jose Rafael\\Desktop\\Coding Dojo\\Add to Cart\\cart.html","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","dateTimeDisplayMode":"Absolute","installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":false,"toolsToAutoPatch":["vite","angular","jest","webpack","next.js","nest.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false,"predictiveLoggingEnabled":false,"allowConsoleLogToTriggerPredictions":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","DESKTOP-MJN4BQE","192.168.1.200"],"host":"127.0.0.1"}
11:44:53.907 info host starting tools discovery and integration
11:44:53.915 info host looking for tools to patch
11:44:53.945 info host found 1 tool file(s) to patch
11:44:53.946 info host patching c:\Users\Jose Rafael\.vscode\extensions\ritwickdey.liveserver-5.7.9\node_modules\live-server\index.js
11:44:53.947 info host worker Starting Host Worker...
11:44:53.952 info host completed tools discovery and integration
11:44:54.075 info buildHook-11156 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
11:44:54.075 info buildHook-11156 running tools: live-server-extension
11:44:54.083 info host client connected: buildHook { address: '::', family: 'IPv6', port: 55908 }
11:44:54.084 info buildHook-11156 allowed tools: vite, angular, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, live-server-extension, live-preview-extension, node
11:44:54.084 info buildHook-11156 running tools: live-server-extension

What should I do?

**Comment by ArtemGovorov** [comment]
@Rafa2908 How do you run/start your code/app?

**Comment by Rafa2908** [comment]
I use the code runner extension. 
I tried node as well.

**Comment by ArtemGovorov** [comment]
@Rafa2908 Code runner extension is not supported by Console Ninja. Please check the list of the supported tech at https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#supported-technologies, running node is supported, see https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#universal-node-applications. 

Also, if you are running small code samples as opposed to a bigger app, our other extension may be a better choice for your scenario, please check out https://quokkajs.com/.
