### ISSUE TITLE
console ninja does not work with angular cli app

### ISSUE THREAD

**Issue by christian-cell** [wallabyjs/console-ninja#188]
### What happened?

i was expecting console ninja print a test boolean var setted true

### Version

v0.0.197

### Steps to reproduce (or sample repo)

in angula project , node version: 18.15.0 , angular version: 15.2.4 , npm 9.6.2 , create project ng new myApp ,console.log(true)

### Log output

```shell
no outpuot
```

**Comment by christian-cell** [comment]
the only diference i need start project with ng serve

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you provide the details requested, we will re-open the issue.
