### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nadeemholofy** [wallabyjs/console-ninja#189]
### What happened?

Violating Google Chrome extension guidelines, When generating a build if  Console NInaj ext is present in VS Code.

Code Readability Requirements
Violation reference ID: [Red Titanium](https://developer.chrome.com/docs/webstore/troubleshooting/#obfuscation)
Violation: Having obfuscated code in the package.
Violating content:
Code snippet: contentScript.js: _0x230995=_0x413f;(function(_0x1f53c0,_0x363b1b){var _0x271a83=_0x413f,_0x5e0775=_0x1f53c0()
Code snippet: popup.js: _0x230995=_0x413f;(function(_0x1f53c0,_0x363b1b){var _0x271a83=_0x413f,_0x5e0775=_0x1f53c0(

### Version

v0.0.199

### Steps to reproduce (or sample repo)

Just create a Chrome Extension build while having this extension in your VS Code.

### Log output

```shell
Violating content:
Code snippet: contentScript.js: _0x230995=_0x413f;(function(_0x1f53c0,_0x363b1b){var _0x271a83=_0x413f,_0x5e0775=_0x1f53c0()
Code snippet: popup.js: _0x230995=_0x413f;(function(_0x1f53c0,_0x363b1b){var _0x271a83=_0x413f,_0x5e0775=_0x1f53c0(
```

**Comment by smcenlly** [comment]
Thanks for using Console Ninja!

The behavior you describe is by design, and is how Console Ninja functions. This is fully described in [our docs](https://github.com/wallabyjs/console-ninja#how-does-it-work):

> Console Ninja integrates with locally installed tools that are building/preparing your code, and then inspects and adjusts your code (in a way that doesn't change how it executes) before it gets to the runtime (browser or node process that runs the code).
> 
> To integrate with supported tools seamlessly, Console Ninja patches your locally installed node modules. When you stop Console Ninja in the editor with the `Pause` command, all patches are removed.
> 
> Console Ninja detects if you are running your tool in production mode (by checking CLI flags and process environment variables). When production mode is detected, the tool will not modify your application code even if Console Ninja is running. In the (unlikely) case that you are running production builds on your local dev computer and are deploying or sharing local builds outside of your machine, we recommend running the Console Ninja `Pause` command in your editor prior to running your build to guarantee that no instrumented code ends up in your production code.
> 
> Console Ninja instrumentation is limited to sending runtime values for `console.log` and errors to your locally running editor only (`localhost` hosted websocket server). The runtime data from your app is **never** sent outside of your local machine. If the code of your application is somehow instrumented by Console Ninja and then used outside of your local machine for some reason:
> 
> - in browser, it will simply do nothing if the app host is not `127.0.0.1`, `localhost`, or one of your network adapter's IP v4 addresses. To connect from a different host name, use the `console-ninja.allowedHosts` VS Code setting.
> - in node, it will fail to connect to `localhost` and will not stop your app from working.

---

If you do **not** use your local development version for deploying your production system, this shouldn't cause a problem. 

If you **do** use your local development version to build your application, you should use the `Pause` command to remove all patches if you do need to build from your local environment.

---

We would also appreciate if you can provide a sample of your project so we can investigate how to detect **build** vs. **dev** so that others don't have the same problem in the future if they are building from their local environment.

**Comment by nadeemholofy** [comment]
we are differentiating the build vs dev with the following package scripts.

1. start-staging
2. start-prod

in each of the above, the env we are looking for is REACT_APP_ENV , which is staging  in case of start-staging and prod in case of start-prod.

**Comment by smcenlly** [comment]
Thanks for letting us know. We've updated Console Ninja to check for `REACT_APP_ENV` being `prod` or `production` so that Console Ninja won't add its instrumentation in this case.

We still recommend using the `Pause` feature if you are building from your local development machine.
