### ISSUE TITLE
[Feature]: A command to remove all logpoints (breakpoints) for a file

### ISSUE THREAD

**Issue by evanliomain** [wallabyjs/console-ninja#191]
### Describe the feature you'd like.

When you finish a hard debug session where you add logpoints accross many files in your project, it could be great to remove all logpoints you added in 1 command.

Also, a command to remove all logpoints on a file.

**Comment by smcenlly** [comment]
The Logpoints are simply VS Code breakpoints, so you may use the VS Code built-in command, `Remove All Breakpoints` to remove all breakpoints.

Right now, VS Code doesn't have a command to remove all breakpoints on a file. I'll repurpose your issue request for that purpose.

**Comment by mburnell** [comment]
Console Ninja `1.0.174` includes a new command: `Console Ninja: Remove all Breakpoints in File`. This command can be used to clean up logpoints as desired.
