### ISSUE TITLE
[Feature]: Option to make the popover resizeable and persistent with close button

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#193]
### Describe the feature you'd like.

Hi Wallaby Team, 

Again I wanna thank you for this awesome tool CN is really one of the best tools as a JS developer. It's keeping my sanity in check with JS debugging lol. I can't wait to subscribe with the Pro plan to give credit to all of your hardwork. 

I think it's also nice if we can make the popover a bit resizable instead of having a fixed widht or height. 
Sometimes I just dont want to look into the "console output: because it's too crowded" (Tho I know we have filters for that)
But would it be nice if you just look straight into the point of intereest through the popover window without having to navigate or open the console output window.

Also makoing the popover more persistent and close it by demand using a close button. What do you think? 

![image](https://github.com/wallabyjs/console-ninja/assets/65213312/3615fb44-1777-45d8-8449-a629fef688ee)

Thank you!!

**Comment by ArtemGovorov** [comment]
Hey, thanks for being our long time user and for your kind words! Also appreciate posting the feature request.

Wr are using VS Code Hover API to display the popup and right now it is the only way to display such popups in VS Code. Unfortunately the API doesn't let us to control closing it or to make it resizable.

Having said that, some of your use cases can be addressed today:
- VS Code hover is already resizable horizontally (also the modified size seems to be saved by VS Code):
![1](https://github.com/wallabyjs/console-ninja/assets/979966/467e8be6-53ec-4a92-a598-7ae261bb11ee)
- when Console Output gets too crowded, apart from the filtering option that you have mentioned, it's possible to open a specific value of interest quickly:
  - you may use [watchpoint](https://github.com/wallabyjs/console-ninja#watchpoints) to quickly get the pinned view of the value you are after without the rest of the output:
  ![2](https://camo.githubusercontent.com/a7c25550d798e3d6f63eeb88b5a8a9fdc6947f5244d0feac2618cc26e009bc81/68747470733a2f2f636f6e736f6c652d6e696e6a612e636f6d2f696d616765732f646f63732d7761746368706f696e74732e676966)
  - if you use the `Show Output` command (via command palette, lightbulb `Cmd/Ctrl + .` quick action, or the rightmost icon in the hover popup on your screenshot), it should open console output window and expand/focus just that entry for you. So while it's still opening the potentially crowded output, at least what you are after is opened/expanded and focused.

If in future VS Code provides some API to render arbitrary popup widgets, we will definitely try to use them for the features you are suggesting.

**Comment by omerson-cruz** [comment]
Wow. I'm so amazed by how fast you've implemented this feature. Thank you so much , you guys really rock! 💯 💯 💯
