### ISSUE TITLE
[Bug]: Permission Denied after update v0.0.208

### ISSUE THREAD

**Issue by gzimbron** [wallabyjs/console-ninja#194]
### What happened?

Hello, I'm facing a new issue after update from v0.0.207 to v0.0.208 or .209.

After update when I try to run an npm script. sh: Permission denied error is output.

 
Solved temporally:
* Downgrade cConsole Ninja extension to v0.0.207 
* delete node_modules directory: rm -rf node_modules
* re install deps: npm i
* run: npm run dev

Here you have a video explaining this error:
https://share.cleanshot.com/n9b2nrRQ

### Version

0.0.208 +

### Steps to reproduce (or sample repo)

To work: downgrade console ninja to v0.0.207
* Create a skeleton svelte project: ```npm create svelte testapp```
* Install deps and run: npm i and then npm run dev
* Upgrade console ninja and refresh vscode.
* try to run: npm run dev

### Log output

```shell
pruebaejec npm run dev

> pruebaejec@0.0.1 dev
> vite dev

sh: /Users/gzimbron/development/svelte/pruebaejec/node_modules/.bin/vite: Permission denied
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. We accidentally introduced a breaking change with some improvements yesterday.

Please update to the latest version of Console Ninja, `v1.0.210`, it should fix your problem.

**Please note that you will need to run `Console Ninja: Pause` and then `Console Ninja: Start` commands on any affected projects once you get the latest version.**
