### ISSUE TITLE
[Feature]: Show logs on the output panel

### ISSUE THREAD

**Issue by gersanco** [wallabyjs/console-ninja#196]
### Describe the feature you'd like.

I think a great feature will be to show the output in the panel.
<img width="1367" alt="image" src="https://github.com/wallabyjs/console-ninja/assets/12337026/659067ce-5ffc-441f-9d29-3b207655c6dd">

**Comment by smcenlly** [comment]
From [our docs](https://github.com/wallabyjs/console-ninja#log-viewer):

> The log viewer can be displayed in two modes, either `Beside File` and `In View`, there is a setting to configure the mode.
> 
> ![status](https://camo.githubusercontent.com/9ba7de9d159e4643c14268e57c395268b04644f5c45c23953243099318ab4582/68747470733a2f2f636f6e736f6c652d6e696e6a612e636f6d2f696d616765732f646f63732d766965772e676966)
> 
> In the `Beside File` mode (default, and recommended), the viewer is displayed in a new separate editor group to the left from your current editor. In this case, the view behaves like other opened editor tabs, i.e. it is visible in the `Opened Editors` in VS Code file explorer view.
> 
> In the `In View` mode, the viewer is displayed as VS Code side view. The view can also be moved to another VS Code panel. The recommended position for the viewer is to the right of the VS Code `Output` view in the bottom pane of your editor.
