### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/console-ninja#20]
From product hunt:

> Hey nice work, but what about Next 3 support?

**Comment by patroza** [comment]
@ArtemGovorov Nuxt 3 :)

**Comment by smcenlly** [comment]
We've added support for the latest version of `nuxt`. Please update to Console Ninja `v0.0.42`, it should work for you with your `nuxt` project.

<img width="966" alt="image" src="https://user-images.githubusercontent.com/2074089/207515721-a36a4322-f013-4033-921b-79fe5e0bbfba.png">

**Comment by patroza** [comment]
@smcenlly thanks guys, appears to work!

**Comment by tobychidi** [comment]
Okay. I have been enjoying Console Ninja on my Nuxt 3 project as well.  I have a problem though. I don't see logs from Nuxt server routes.

**Comment by smcenlly** [comment]
@tobychidi - we tried using https://github.com/nuxt/movies and it's working for us.

Can you please [create a new issue](https://github.com/wallabyjs/console-ninja/issues/new?assignees=&labels=bug%2Crequires+triage&projects=&template=bug.yml&title=%5BBug%5D%3A+) and provide steps to reproduce your problem?

**Comment by tobychidi** [comment]
@smcenlly I have created issue #324 that clarifies what I was asking about. Thank you.
