### ISSUE TITLE
[Bug]: console ninja is waiting for webpack, to start. console ninja has succesfuly integrated to webpack and jest found in your project but has no conected to a running instance of it yet

### ISSUE THREAD

**Issue by cedricbreuleux** [wallabyjs/console-ninja#201]
### What happened?

After a reboot pc,

i have this error:

console ninja is waiting for webpack, to start. console ninja has succesfuly integrated to webpack and jest found in your project but has no conected to a running instance of it yet

### Version

v0.0.220

### Steps to reproduce (or sample repo)

i just npm start my project and try console.log something after start NINja

### Log output

```shell
the log error:

14:09:59.610 info host ------------ starting ------------
14:09:59.622 info extension 
14:09:59.650 info host client connected: extension { address: '::', family: 'IPv6', port: 46343 }
14:09:59.653 info host starting host: {"extensionFolder":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220","runtimeHookFile":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/cece_la_baie/Documents/repo/Previouslyon/src/index.js","reason":"search"},{"path":"/home/cece_la_baie/Documents/repo/Previouslyon/src/Function.js","reason":"open"},{"path":"/home/cece_la_baie/Documents/repo/Previouslyon/src/component/MesSeries/Mes_series.js","reason":"search"},{"path":"/home/cece_la_baie/Documents/repo/Previouslyon/src/component/Accueil/Accueil.js","reason":"open"},{"path":"/home/cece_la_baie/Documents/repo/Previouslyon/babel.config.js","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","CeceLaBaieLaptop","10.22.255.172"],"host":"127.0.0.1"}
14:09:59.673 info host starting tools discovery and integration
14:09:59.680 info host looking for tools to patch
14:09:59.850 info host worker Starting Host Worker...
14:10:00.070 info host found 5 tool file(s) to patch
14:10:00.072 info host patching /home/cece_la_baie/.vscode/extensions/ritwickdey.liveserver-5.7.9/node_modules/live-server/index.js
14:10:00.073 info host patching /home/cece_la_baie/Documents/repo/Previouslyon/node_modules/webpack/lib/index.js
14:10:00.073 info host patching /home/cece_la_baie/Documents/repo/Previouslyon/node_modules/webpack/lib/webpack.js
14:10:00.073 info host patching /home/cece_la_baie/Documents/repo/Previouslyon/node_modules/jest/bin/jest.js
14:10:00.073 info host patching /home/cece_la_baie/Documents/repo/Previouslyon/node_modules/jest-runner/build/testWorker.js
14:10:00.075 info host completed tools discovery and integration
```

**Comment by ArtemGovorov** [comment]
> just npm start my project

From your log It looks like the extension has started correctly, but then your build tool is not connecting to the extension for some reason.

Is it the full trace.log file content **after** you open the project and run npm start?

Can you please share what does your `npm start` command do?

**Comment by cedricbreuleux** [comment]
yes its the full trace..

sure, see the npm start:

Compiled successfully!

You can now view previouslyon in the browser.

  Local:            http://localhost:3001
  On Your Network:  http://10.22.255.172:3001

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully

**Comment by ArtemGovorov** [comment]
Can you please share your `package.json` file?

**Comment by cedricbreuleux** [comment]
sure ! :)

{
  "name": "previouslyon",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "bootstrap": "^5.3.1",
    "crypto": "^1.0.1",
    "crypto-js": "^4.1.1",
    "jest": "^27.5.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-modal": "^3.16.1",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@babel/preset-react": "^7.22.15",
    "react-router-dom": "^6.15.0",
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4"
  }
}

**Comment by ArtemGovorov** [comment]
Thanks, I have created a sample repo https://github.com/wallabyjs/cn-201 with your `package.json` file, added some stock CRA generated files and everything seems to be working:

<img width="669" alt="Screen Shot 2023-09-14 at 6 08 46 pm" src="https://github.com/wallabyjs/console-ninja/assets/979966/59445a14-adfb-45bf-88ac-dad9c2217568">

Please try cloning the repo, running `npm i`, and checking if Console Ninja works.

If the sample repo still doesn't work, please clear your Ninja `trace.log` file,  run `npm run start` again and share the log's content.

If the sample repo works, please try removing your `node_modules`, running `npm i` and then `npm run start` again. If it still doesn't help, please try cloning your repo to a different folder, then install node modules and run `npm run start`.

**Comment by cedricbreuleux** [comment]
thanks, for help,
i clone your repo, npm i and npm run start

on the start i have this error:
[eslint] package.json » eslint-config-react-app/jest#overrides[0]:
	Environment key "jest/globals" is unknown

if i closed error en try console.log
i have this error:

[eslint] package.json » eslint-config-react-app/jest#overrides[0]:
	Environment key "jest/globals" is unknown
ERROR in [eslint] package.json » eslint-config-react-app/jest#overrides[0]:
	Environment key "jest/globals" is unknown


webpack compiled with 1 error

**Comment by ArtemGovorov** [comment]
I'm not sure what's causing the eslint error in the sample repo, it's working for me without any issues. The eslint should be irrelevant anyway, so can you please try getting latest from the repo, I have [removed eslint config from package.json](https://github.com/wallabyjs/cn-201/commit/7d8daa2550569146d969803a4201596807f57c06).

**Comment by cedricbreuleux** [comment]
the log traces this filled only when I reset ninja, and not if I do npm run start

if i restart manualy ninja see the log trace:

10:39:32.584 info extension stopping host
10:39:32.602 info host removing cache folder: 71bece2a9d4ffd787808c0325cb2bd9a
10:39:32.615 info extension client disconnected: 1006 
10:39:32.616 info buildHook-48531 client disconnected: 1006 
10:39:32.617 info buildHook-48531 disconnected from host: 42147
10:39:32.875 info extension host process output: port:[42147]
10:39:32.863 info host ------------ starting ------------
10:39:32.875 info extension 
10:39:32.899 info host client connected: extension { address: '::', family: 'IPv6', port: 42147 }
10:39:32.900 info host starting host: {"extensionFolder":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220","runtimeHookFile":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/cece_la_baie/.vscode/extensions/wallabyjs.console-ninja-0.0.220/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/cece_la_baie/Documents/repo/cn-201/src/index.js","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","showDateTime":true,"installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":15000,"fontSize":10,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","CeceLaBaieLaptop","10.22.255.172"],"host":"127.0.0.1"}
10:39:32.914 info host starting tools discovery and integration
10:39:32.920 info host looking for tools to patch
10:39:33.073 info host worker Starting Host Worker...
10:39:33.302 info host found 5 tool file(s) to patch
10:39:33.304 info host patching /home/cece_la_baie/.vscode/extensions/ritwickdey.liveserver-5.7.9/node_modules/live-server/index.js
10:39:33.305 info host patching /home/cece_la_baie/Documents/repo/cn-201/node_modules/webpack/lib/index.js
10:39:33.305 info host patching /home/cece_la_baie/Documents/repo/cn-201/node_modules/webpack/lib/webpack.js
10:39:33.306 info host patching /home/cece_la_baie/Documents/repo/cn-201/node_modules/jest/bin/jest.js
10:39:33.306 info host patching /home/cece_la_baie/Documents/repo/cn-201/node_modules/jest-runner/build/testWorker.js
10:39:33.307 info host completed tools discovery and integration

**Comment by ArtemGovorov** [comment]
So just to confirm, when you do `npm run start`, no log entries are appened?

Can you please run `node -v && npm -v` in the same terminal where you run `npm run start` and share the output?

**Comment by cedricbreuleux** [comment]
yes, trace log is only filled when I open vscode or restart manually ninja and not npm run start



here my terminal:
cece_la_baie@CeceLaBaieLaptop:~/Documents/repo/cn-201$ node -v
v12.22.9
cece_la_baie@CeceLaBaieLaptop:~/Documents/repo/cn-201$ npm -v
8.5.1
cece_la_baie@CeceLaBaieLaptop:~/Documents/repo/cn-201$

**Comment by ArtemGovorov** [comment]
It looks like your version of node (`v12.22.9`) is too old and may not be supported. v12 reached its [end-of-life over a year ago](https://endoflife.date/nodejs). Try updating your node version to a more recent one, like 18 or 20, and check it helps.

**Comment by cedricbreuleux** [comment]
I updated node, it works now,
I don't understand because I reinstalled Ubuntu with the latest version and I also thought I had the latest version of node,

thank you very much for your time and help

**Comment by ArtemGovorov** [comment]
No problem at all, glad to hear it helped!
