### ISSUE TITLE
Chorded "Escape" keybinding applied to all editors.

### ISSUE THREAD

**Issue by phyllisstein** [wallabyjs/console-ninja#21]
The default keybinding for `console-ninja.clearOutput` causes <kbd>Escape</kbd> to be chorded in all editors. I was able to fix it by grouping the `when` criteria that followed `||`:

```json
{
  "key": "escape escape",
  "command": "console-ninja.clearOutput",
  "when": "activeWebviewPanelId == 'console-ninja.output' || (editorTextFocus && !editorHasSelection && !findWidgetVisible && !inReferenceSearchEditor && !parameterHintsVisible && !quickFixWidgetVisible && !referenceSearchVisible && !renameInputVisible && !suggestWidgetVisible)"
}
```

I'm not persuaded that's the smartest way to do it, but it did it.

**Comment by smcenlly** [comment]
We've removed the default keybinding for `Clear Output`, we don't believe it's really required and users can create their own binding if they like.
