### ISSUE TITLE
High CPU Usage and Sluggish Performance in VSCode Due to Console Ninja Extension

### ISSUE THREAD

**Issue by Mel-TB** [wallabyjs/console-ninja#214]
Type: <b>Bug</b>

Problem Description:
When the Console Ninja extension is enabled, it causes VSCode to use 100% CPU, leading to significant performance issues, including lag.

Steps to Reproduce:
Enable Console Ninja extension.
Open a project in VSCode.
Observe the CPU usage and performance degradation.
Expected Behavior:
With the Console Ninja extension enabled, VSCode should not cause such high CPU usage and sluggish performance.

Actual Behavior:
CPU usage spikes to 100%, and VSCode becomes slow and unresponsive.

Additional Information:
VSCode version: 1.83.1
Node.js version: 18.15.0
Console Ninja extension version: 1.0.232
Operating System: Windows x64

Possible Workaround:
As a temporary solution, you can disable the Console Ninja extension, which immediately resolves the issue with CPU usage and performance.

Extension version: 1.0.232
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (18.91GB free)|
|Process Argv|--crash-reporter-id 47de95d9-9d59-4354-9442-a6bfa60356a8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
vscrpc:30673769
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30821571
dsvsc015:30845448
pythonregdiagcf:30859692

```

</details>

**Comment by smcenlly** [comment]
Can you please copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory?

**Comment by ArtemGovorov** [comment]
Closing this issue as we haven't heard back. If you're still having issues, please share the [requested details](https://github.com/wallabyjs/console-ninja/issues/214#issuecomment-1762314471) and we'll reopen the issue.
