### ISSUE TITLE
[Bug]: Single line returns always returning when logging an entire function

### ISSUE THREAD

**Issue by BrandonALittle** [wallabyjs/console-ninja#218]
### What happened?

When using console ninja, with NextJS, I have a component that contains the following pattern:

```
export const MyComponent = () => {
...
  if (condition) return <OtherComponent />

  return null
}
```

When I add a Console Ninja breakpoint to the line `export const MyComponent = () => {`, the condition never fails, so the component ALWAYS returns `<OtherComponent />. Adding curly braces to the return statement resolves the issue, but since single line returns are common in our codebase, this could be an issue that creates false positives/negatives. 

### Version

1.0.233

### Steps to reproduce (or sample repo)

Use a component with conditional render logic, with a single line return following the condition, with no curly braces. Add a breakpoint to the component declaration line. See that the behavior of the component differs based on the breakpoint and/or curly braces.

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is published in v1.0.243+.
