### ISSUE TITLE
[Feature]: tsc build is not supported?

### ISSUE THREAD

**Issue by mozart25** [wallabyjs/console-ninja#221]
### Describe the feature you'd like.

Is tsc compiler not working with console ninja? if not, then i can't use tsc with console-ninja? or are there any ways to handle this?

My tsconfig.json is 

`{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "lib": ["DOM", "ESNext"],
    "allowJs": true,
    "incremental": false,
    "sourceMap": true,
    "outDir": "./build"
  }
}
`
![스크린샷 2023-10-24 오전 10 40 33](https://github.com/wallabyjs/console-ninja/assets/49587839/8296ea69-a529-4258-ad25-cc3089a44a2e)

**Comment by smcenlly** [comment]
Based on your photo, it doesn't look like you are using one of [our supported tools](https://github.com/wallabyjs/console-ninja#supported-technologies).

You may instead try running your development environment using our [Universal Node applications support](https://github.com/wallabyjs/console-ninja#universal-node-applications). This should work for you if your dev tool chain uses `tsc`.

If that doesn't help, please provide us with steps to reproduce your issue or else provide a sample repo that has your problem.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Hopefully our suggestion to use our [Universal Node applications support](https://github.com/wallabyjs/console-ninja#universal-node-applications) addressed your issue.
