### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fmcnulty** [wallabyjs/console-ninja#224]
### What happened?

I was expecting console ninja to work

### Version

v1.0.243

### Steps to reproduce (or sample repo)

running a nextjs app (13.4.6), however it is stuck on inactive. It had been working fine for weeks however i cannot seem to getting it running anymore.

### Log output

```shell
no log output, it just isnt running.
```

**Comment by ArtemGovorov** [comment]
We have tried and next.js app (including v13.4.6) is working for us with Console Ninja.

- Please share a screenshot the [status of the extension](https://github.com/wallabyjs/console-ninja#troubleshooting).
- Please copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory.

**Comment by fmcnulty** [comment]
I think the issue arose from conflicts between a yarn.lock file and package-lock.json file. I have managed to fix now, thanks for your reply anyway.
