### ISSUE TITLE
[Bug]: React modules with `'use client'` can result in an error

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/console-ninja#227]
### What happened?

Using file code coverage breaks react server components  when the `'use client'` directive is used in the module.

The `'use client'` needs to be at the very top of the module, and console ninja inserts code related to file coverage above it.

This breaks using Next.js, which throws an error if the directive is not found at the top of the module, but the issue should be present with any framework that supports RSC and `'use client'`, as per [the docs](https://react.dev/reference/react/use-client) this always needs to be at the very top.

### Version

1.0.250

**Comment by ArtemGovorov** [comment]
The issue is fixed and the fix is published in v1.0.251+.
