### ISSUE TITLE
[Bug]: Unable to verify pro license behind ZScaler VPN

### ISSUE THREAD

**Issue by hanneswidrig** [wallabyjs/console-ninja#234]
### What happened?

I just purchased the Pro version of Console Ninja and I was looking to activate it in VSCode. When I attempt to "Activate License" I'm met with errors on the UI, and in the Main output of VSCode I see the error.

```
[error] Blocked vscode-webview request vscode-webview://1tjkggsp0k9ucv4p0895i1m3ev03pqcefrtman7feue032i5erp5/index.html?id=b9d0c250-9a42-41a6-8aa4-e56ec4f47d7c&origin=8d16be92-84c3-4c3a-af9b-e4e52ef454ff&swVersion=4&extensionId=WallabyJs.console-ninja&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app
```

<img width="434" alt="image" src="https://github.com/wallabyjs/console-ninja/assets/3399497/4c2be0d7-5db6-40ee-a407-7905d34128da">

### Version

v1.0.260

### Steps to reproduce (or sample repo)

In the description above

### Log output

```shell
[error] Blocked vscode-webview request vscode-webview://1tjkggsp0k9ucv4p0895i1m3ev03pqcefrtman7feue032i5erp5/index.html?id=b9d0c250-9a42-41a6-8aa4-e56ec4f47d7c&origin=8d16be92-84c3-4c3a-af9b-e4e52ef454ff&swVersion=4&extensionId=WallabyJs.console-ninja&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app
```

**Comment by smcenlly** [comment]
It looks like ZScaler is the cause of your problem. It's not allowing us to connect to our backend service at `https://licensing.wallabyjs.com/licensing`. 

You may try to add our URL to your allow lists (https://help.zscaler.com/zia/adding-urls-allowlist) to fix the problem.

If you're still having problems, you should be able to temporarily disable your VPN, active Console Ninja, and then it will work for you. You will need to do this at the end of each billing period to update your license.

If you're still having problems, please [email us](hello@wallabyjs.com) using the email address associated with your purchase.
