### ISSUE TITLE
[Help]:  Is VS Code's Run and Debug using a launch.json file supported?

### ISSUE THREAD

**Issue by raykoziel** [wallabyjs/console-ninja#243]
### Describe the feature you'd like.

I have recently installed the Console Ninja extension v 1.0.266 to VS Code for use with a Node.js application.  This application is launched by using VS Code's Run and Debug via a launch,json file.  After installing Console Ninja and restarting VS Code, I tried launching the app but Console Ninja did not start up.  I then tried Console Ninja: Start from the command palette and that did start up Console Ninja.  When I hovered over the Console Ninja icon in the status bar, the following displayed:

![2023-12-01_13-40-54](https://github.com/wallabyjs/console-ninja/assets/123186071/5f6b4acd-dc6d-4aa8-b7bd-c1f9da1a3d03)

Does this mean that Console Ninja cannot be used with the application in question because it is not using any of the dependencies listed that Console Ninja can hook into, or it there another way to use Console Ninja with VS Code's Run and Debug and launch.json?

Thank you!

**Comment by smcenlly** [comment]
We don't provide first class integration for Console Ninja running within VS Code.

It may be possible to start Console Ninja with VS Code as a [Universal Node Application](https://github.com/wallabyjs/console-ninja#universal-node-applications), but we haven't tried this before.

We'll take a look early next week and get back to you whether this is possible. If you try starting Console Ninja as a universal application and you get it working, please let us know.

**Comment by mburnell** [comment]
We've now taken a look at this, and it seems to work correctly. As suspected, using the [Universal Node Application](https://github.com/wallabyjs/console-ninja#universal-node-applications) approach will get things instrumented correctly. To do this you'll need to identify the appropriate place in your toolchain to wrap in a `console-ninja` call. In our simple experiment, we adjusted the `watch` task:

```
  "watch": "console-ninja tsc -watch -p ./",
```

With this in place you can:
1. Make sure Ninja isn't paused
2. Kill any running / watching tasks (often configured to start when the project is opened)
3. F5 / run

Subsequent actions that are covered by console.logs / logpoints should appear as desired.
