### ISSUE TITLE
[Bug]: The new tooltip feature is blocking the console output view. Please add an 'X' button to close it.

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#244]
### What happened?

I was expecting to be able to click the link on the console log but I was not able to do so because the new tooltip (with code overview is blocking the console output view when it's window is small). 

Please see the screen capture for what I'm referring to. 

Btw Console Ninja rocks and keeps on improving and adding more features to make our lives easier as JS developers..
Kudos to the Wallaby team. :)

### Version

V1.0.266

### Steps to reproduce (or sample repo)

1. Trigger console ninja to produce an output in the console log output view. 
2. Tries to click one of the link to open the actual source code.
3. I'm not able to clikc the link because the tooltip is blocking the link :(

https://github.com/wallabyjs/console-ninja/assets/65213312/6d03cf09-7499-4fe3-aded-239de3cbdb48

### Log output

```shell
N/A
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.267 of the extension. Now the header of the displayed code preview widget is clickable, it navigates and closes the widget on click.
