### ISSUE TITLE
[Bug]: Typescript errors in project when enabling extension

### ISSUE THREAD

**Issue by markmxr** [wallabyjs/console-ninja#245]
### What happened?

When enabling the extension on vscode my server cannot run because of a typescript error. Disabling the extension, I can run the API normally. The server is running on typescript version 4.7.4. 

Is the typescript version in the extension is overriding the project's?

### Version

v1.0.267

### Steps to reproduce (or sample repo)

Enable the extension
Expect the the server just works

### Log output

```shell
Probably not needed since this is not an error within console ninja itself
```

**Comment by smcenlly** [comment]
Console Ninja does not ship with or use TypeScript as part of its runtime. We expect that there may be a bug when Console Ninja is processing your TypeScript files for your project when it's running for your project, and that's what is causing your problem.

Can you please provide details of the error, and your Console Ninja log output from the `~/.console-ninja/trace.log` file in your user home directory. If there's a specific file that Console Ninja is breaking on, can you also please provide the content of that file (or else create a minimal reproducible example)?

**Comment by markmxr** [comment]
@smcenlly Thanks for the response - not sure what was going on but seems like everything is working now. If I were to guess there was something wrong with my environment, specifically around node packages. Everything works now so closing this out!
