### ISSUE TITLE
[Bug]: The body of an 'if' statement cannot be the empty statement.

### ISSUE THREAD

**Issue by shaun-funke** [wallabyjs/console-ninja#266]
### What happened?

Single line if statements compile with an added semi-colon, rendering an error. Using TypeScript and Jest in VsCode.

For example: 
`if (someValue) console.time(time)` compiles to 
`if (someValue) /* eslint-disable */;(oo_ts(),console.time(time))`

Error occurs:
`error TS1313: The body of an 'if' statement cannot be the empty statement.`

### Version

v1.0.285

### Steps to reproduce (or sample repo)

run jest tests with sample code

### Log output

```shell
`error TS1313: The body of an 'if' statement cannot be the empty statement.`
```

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. It's now fixed and the fix is published in v1.0.286 of the extension.
