### ISSUE TITLE
[Feature Request] - Console Ninja through winston (or similar) loggers

### ISSUE THREAD

**Issue by adidaslevy** [wallabyjs/console-ninja#276]
### Issue description or question

Usually when working on an enterprise grade product, a logger package is used, such as winston - which contains many transports: console, filebeat, etc. 

Currently, when console.ninja is integrated to a project, it shows the winston source code, and not the actual log line that produced the log.

**Comment by smcenlly** [comment]
Closing as a duplicate. Please subscribe to https://github.com/wallabyjs/console-ninja/issues/35 for updates.
