### ISSUE TITLE
[Feature]: Add a setting to launch console ninja when VSCode is opened

### ISSUE THREAD

**Issue by gersanco** [wallabyjs/console-ninja#285]
### Describe the feature you'd like.

Sometimes, when I open the VSCode, I forget to start the Console Ninja, It would be nice if you add a setting to launch it when the VSCode is opened.

Thanks in advance

**Comment by smcenlly** [comment]
Once you explicitly start Console Ninja on a project, Console Ninja should remember that it was started for that project the next time you open it.

If you have a project that includes any dependencies that are supported by Ninja, then Ninja should always start for you automatically.

---

If our response doesn't help, could you please provide additional detail on the steps that you're taking when you need to launch Console Ninja so we can better understand your problem?

**Comment by gersanco** [comment]
> Once you explicitly start Console Ninja on a project, Console Ninja should remember that it was started for that project the next time you open it.
> 
> If you have a project that includes any dependencies that are supported by Ninja, then Ninja should always start for you automatically.
> 
> If our response doesn't help, could you please provide additional detail on the steps that you're taking when you need to launch Console Ninja so we can better understand your problem?

Hello,

In my case (using the VSCode extension) every time that I close the VsCode (all of its instances) or shut down the laptop when I open it again, I have to "Start Console Ninja" because is on "Pause".

I'm using a MacBook Pro with an M1, and my project is using NX and NextJs.

**Comment by ArtemGovorov** [comment]
@gersanco Can you please:
- have your project opened, start Ninja,
- close the VsCode (all of its instances)
- open your project in VS Code, check if Ninja is paused,
- archive the `~/.console-ninja` folder and attach the archive to this issue (or email it to us hello@wallabyjs.com)?

**Comment by gersanco** [comment]
Hello, I just sent the traces to the email, thanks

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.
We have released new version of Console Ninja v1.0.303 with a fix, so after updating to the new version, and unpausing Ninja for the project, everything should work for you.

**Comment by gersanco** [comment]
Yes, it works, thanks so much
