### ISSUE TITLE
[Feature]: Neovim support for Console Ninja

### ISSUE THREAD

**Issue by victorias** [wallabyjs/console-ninja#288]
### Describe the feature you'd like.

Hi, first of all I would love to thank Wallabyjs for such an innovative, incredible tool like Console ninja. It has quickly become my most important tool in my workflow. However, I am predominantly a Neovim user and I would love a Neovim plugin for Console ninja. I realize that Neovim is a relatively niche editor and would be more than happy to contribute to any such effort to getting Console ninja onto Neovim.

Thank you!

**Comment by smcenlly** [comment]
Closing as a duplicate. Please subscribe to https://github.com/wallabyjs/console-ninja/issues/167 for updates.
