### ISSUE TITLE
[Bug]: Console Ninja including message to STDOUT for Serverless commands

### ISSUE THREAD

**Issue by dnicolson** [wallabyjs/console-ninja#289]
### What happened?

The following text appears in STDOUT when running Serverless commands (it's not clear how to disable this):
`✔ Console Ninja extension is connected to Serverless, see https://tinyurl.com/2vt8jxzw`

From a bash script a workaround is to remove the Console Ninja message:
```
#!/bin/bash

OUTPUT=$(sls invoke --stage pro --function export --data $1)
OUTPUT=${OUTPUT:123}
```

### Version

v1.0.312

### CLI command to start your dev tool

No CLI command is used, there is just the Visual Studio Code extension.

### Steps to reproduce (or sample repo)

`sls invoke --stage pro --function export --data test`

### Log output

```shell
09:26:30.742 info buildHook-11106 installing build hook for serverless at /path/to/project, node v18.19.1
```

**Comment by dnicolson** [comment]
This doesn't appear to be functioning properly. On one machine I set this option in VS Code and it worked. On another machine the setting synced but the welcome message still appears.

**Comment by smcenlly** [comment]
@dnicolson - could you please create a new issue and provide us with your diagnostic report when this occurs? 

Our diagnostic report includes the value of this setting that is provided to Console Ninja from your VS Code settings at startup, so it should let us identify whether the setting is wrong, or there's something else wrong with Ninja not using it.

I'm not familiar with exactly how VS Code setting sync works, but it may be that Ninja's host (which starts with your project) starts with the setting before it's synchronised by VS Code. In this case, the first start after the setting changes on another machine may not work, but subsequent starts will.
