### ISSUE TITLE
Support for collapsing nested objects

### ISSUE THREAD

**Issue by alinsalaru** [wallabyjs/console-ninja#29]
Awesome extension, already using it on all of my products! Congrats!

Our team is working with **big big nested objects**.

A good enhancement will be, instead of` JSON.stringify(console)` output, to grant the user the possibility of collapsing or expanding parts of nested objects.

![example](https://user-images.githubusercontent.com/1756716/206663662-35d5ad13-c26f-49dd-8c82-dd98c8e90b5b.gif)

**Comment by smcenlly** [comment]
Nice idea. We had thought the same, something similar to what we have done in Wallaby.js and Quokka.js with our [Value Explorer feature](https://wallabyjs.com/docs/intro/value-explorer.html).

**Comment by ArtemGovorov** [comment]
The [feature](https://github.com/wallabyjs/console-ninja#log-viewer-pro) has been shipped in v0.0.107.
