### ISSUE TITLE
[Feature]: Remove log message from browser console about connection status

### ISSUE THREAD

**Issue by johannesmutter** [wallabyjs/console-ninja#290]
### Describe the feature you'd like.

Since the recent update of the console ninja extension (v1.0.312) the VS Code Plugin now logs this very **EMPHASISED** message for every session. The console should not be polluted with redundant information. It pushes important other log messages to the bottom.

Reasoning:
- Every user of the Plugin knows how this plugin works
- It's obvious enough that it's connected, because the inline logs in VScode indicate it's working, no need to tell explicitly it's working/ connected.

Suggestion:
- remove message (preferred):
- add setting to hide.

![CleanShot 2024-04-23 at 12 40 40@2x](https://github.com/wallabyjs/console-ninja/assets/9489658/c66cc30a-416b-4bde-a8a7-a0887365ac46)

**Comment by ArtemGovorov** [comment]
Thanks for your feedback.

We have added a setting to disable Console Ninja Welcome message displayed in build tools CLI and browser in v1.0.313. You may now use the `console-ninja.showWelcomeMessageInTools` setting in VS Code.
