### ISSUE TITLE
[Bug]:  TypeError: Cannot read properties of undefined (reading 'fetchStack')

### ISSUE THREAD

**Issue by thinke5** [wallabyjs/console-ninja#291]
### What happened?

```js
let a =new Response();console.log(await a.clone().arrayBuffer())
```

A bug will occur when opening

<img width="912" alt="image" src="https://github.com/wallabyjs/console-ninja/assets/33920997/2bf4a8fc-1a7c-462c-96d9-9cfc46dd9ebb">

Doesn't appear after closing

<img width="617" alt="image" src="https://github.com/wallabyjs/console-ninja/assets/33920997/4a4a67b6-662e-48cb-8afe-2af6950900d0">

### Version

1.0.313

### CLI command to start your dev tool

vscode + vite

### Steps to reproduce (or sample repo)

none

### Log output

```shell
none
```

**Comment by mburnell** [comment]
Thanks for reporting the issue. This has been fixed in version `1.0.314`.
