### ISSUE TITLE
[Feature]: Warn when Next.js is started with turbo pack

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/console-ninja#292]
### Describe the feature you'd like.

When `console-ninja.showWelcomeMessageInTools` is enabled (default), warn when Console Ninja is active and next.js is started with turbo pack mode with instructions to run in webpack mode

**Comment by JonParton** [comment]
Fab - thanks for picking up and raising this @smcenlly 🙌

Is this the message that gets injected into the terminal log steam after nextjs starts?

If so, what a perfect place to let people know about this if you can detect turbo mode 🙌

**Comment by smcenlly** [comment]
> Is this the message that gets injected into the terminal log steam after nextjs starts?

Yes, that’s right

**Comment by mburnell** [comment]
This feature is available in Console Ninja version `1.0.316`:

<img width="849" alt="Screenshot 2024-04-29 at 1 58 52 PM" src="https://github.com/wallabyjs/console-ninja/assets/2075770/da67335c-4c15-4f1d-953e-aab70d80e86d">
