### ISSUE TITLE
Using Console Ninja in Nx tool

### ISSUE THREAD

**Issue by Avivbens** [wallabyjs/console-ninja#3]
Hi 👋 

We're using Angular 14, with Nx CLI tool

Any chance to add support for Nx build and serve tool? 
Currently, the extension does not handle and show those logs

**Comment by NikGovorov** [comment]
We do support Nx and Angular 14. Could you please execute the following steps and see if the latest version of Console Ninja works for you?
```
npx create-nx-workspace@15.1.1
# select Integrated
# select angular
# enter nx-ng-fourteen
# enter frontend
# choose CSS
# choose No
cd .\nx-ng-fourteen
code .
npm start
# add console.log('hello world!!!'); to ngOnInit of apps/frontend/src/app/nx-welcome.component.ts
```

**Comment by ArtemGovorov** [comment]
Closing this issue as we require more information and have not heard back. If you reply with the information requested, we will re-open this issue.
