### ISSUE TITLE
[Bug]: Console Ninja is not connecting to a running instance of an Angular project after latest update

### ISSUE THREAD

**Issue by ihouwat** [wallabyjs/console-ninja#302]
### What happened?

Since this past week, Console Ninja no longer works for an Angular project. Instead I see this status message:

![image](https://github.com/wallabyjs/console-ninja/assets/58915539/74c1ab33-4b0e-413b-9f95-67a1b485cde4)

**What I did before reporting the bug**:
* Deleted .angular
* Deleted node_modules
* Reinstalled node_modules

**Some details during troubleshooting**:
- i use **node v14.21.3** (our company policy forces us to use this version for developing our Angular apps)
- i created another project using Jest. Console Ninja similarly did not work with node v14. However, **it works with a more recent version (v18.7.1)**
- Crucially, I **downgraded Console Ninja to v.1.0.320 and it DID work with node v14.21.3** for that Angular project 
![image](https://github.com/wallabyjs/console-ninja/assets/58915539/61e638b2-d1a3-428e-b94b-cb8b03afd0fb)

### Version

1.0.321 (Community edition)

### CLI command to start your dev tool

sudo npm run start

### Steps to reproduce (or sample repo)

1. Install Console Ninja
2. Start the angular app

### Log output

```shell
15:46:23.399 info host worker Starting Host Worker...
15:46:23.408 info host starting tools discovery and integration
15:46:23.416 info host looking for tools to patch
15:46:24.021 info host found 4 tool file(s) to patch
15:46:24.022 info host patching /users/ihouwat/documents/repos/raadm-rating-ui-v01/node_modules/@angular/cli/bin/ng.js
15:46:24.023 info host patching /users/ihouwat/documents/repos/raadm-rating-ui-v01/node_modules/webpack/lib/WebpackOptionsApply.js
15:46:24.023 info host patching /users/ihouwat/documents/repos/raadm-rating-ui-v01/node_modules/webpack/lib/index.js
15:46:24.023 info host patching /users/ihouwat/documents/repos/raadm-rating-ui-v01/node_modules/webpack/lib/webpack.js
15:46:24.111 info host Host's startup and patch time: 1550 ms
15:46:24.111 info host completed tools discovery and integration
15:46:24.116 ERR! host uncaught exception: No clients connected
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem.

This has been fixed in the latest version of Console Ninja, `v1.0.322`.
