### ISSUE TITLE
[Feature]: Copy object or field from VALUES

### ISSUE THREAD

**Issue by R3flector** [wallabyjs/console-ninja#303]
### Describe the feature you'd like.

![cant_copy](https://github.com/wallabyjs/console-ninja/assets/58531356/26839194-b596-48fa-b88b-273144da0f21)

Please add possibility to copy from VALUES
Now neither Ctrl+C is not on the right click it is impossible to copy anything

**Comment by smcenlly** [comment]
`Copy` is available from the selected log entry toolbar and via the `Ctrl/Cmd + C` shortcut:

<img width="1027" alt="image" src="https://github.com/wallabyjs/console-ninja/assets/2074089/ea5b0613-f58c-4c32-aaec-4029c7bf295f">

If you have expanded the log entry, and want to copy the value from this location, you need to first select which text you wish to copy.
