### ISSUE TITLE
[Feature]: Enable console.ninja for Next.js Turbo Application

### ISSUE THREAD

**Issue by xspaceboy** [wallabyjs/console-ninja#308]
### Describe the feature you'd like.

I tried to use the console ninja vscode extension for Next.js turbo repo, and seems like console ninja doesn't support it yet.
Please provide a solution to use this extension for Turborepo based on Next.js

**Comment by mburnell** [comment]
While Console Ninja doesn't currently support Turbopack (see https://github.com/wallabyjs/console-ninja/issues/136 for more details), we've been able to get it running in Turborepo using Webpack (by removing the `--turbo` from the relevant locations in the `package.json` files). Does this work for you?

**Comment by smcenlly** [comment]
Closing this issue - assuming that our suggestion solved your problem.

**Comment by ArtemGovorov** [comment]
Console Ninja now ships with built-in **Turbopack** support. Fire up a modern Next.js project (where `npm run dev` runs Turbopack by default) and Console Ninja will now seamlessly capture and map your runtime logs, errors and network calls just like it does with webpack builds.
