### ISSUE TITLE
Issue with Cypress v10.5

### ISSUE THREAD

**Issue by 8enSmith** [wallabyjs/console-ninja#31]
When I run Cypress with console-ninja installed I get the following error in Cypress:

Error: "Cannot find module 'tslib'

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/798183/206719922-8b1d3180-af75-4ed8-9e6e-3becc8bf085e.png">

I tried disabling Cypress but problem persisted. I had to delete my Cypress cache and reinstall to get the Cypress app working again.

**Comment by ArtemGovorov** [comment]
Thanks for the report. 

The issue with the error is fixed now in the latest published Console Ninja version, so if you re-install/enable the extension, it should not make your Cypress app crash anymore. 

Having said that, in your case it looks like you are using node v12 or below (end-of-life now) that Console Ninja does not support. And while with the latest version of Console Ninja Cypress App will not crash anymore, Console Ninja will not work (we'll also be [implementing user notification re minimum node version](https://github.com/wallabyjs/console-ninja/issues/28)).
