### ISSUE TITLE
Node not working

### ISSUE THREAD

**Issue by aprilllllllll** [wallabyjs/console-ninja#316]
### What happened?

Front end is working properly, but the back end by using node.js is not working.

### Version

 v1.0.329

### CLI command to start your dev tool

Mac

### Steps to reproduce (or sample repo)

npm install -g console-ninja 
source console-ninja 
node app.js
error message:
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module '<REPLACE>'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at internalRequire (node:internal/modules/cjs/loader:174:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1433:5)
    at loadPreloadModules (node:internal/process/pre_execution:598:5)
    at setupUserModules (node:internal/process/pre_execution:117:3)
    at prepareExecution (node:internal/process/pre_execution:108:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:37:3)
    at node:internal/main/run_main_module:10:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

Node.js v18.17.0

### Log output

```shell
00:51:11.125 info host ------------ starting ------------
00:51:11.142 info extension host process output: port:[64488]
00:51:11.142 info extension 
00:51:11.156 info host client connected: extension { address: '127.0.0.1', family: 'IPv4', port: 64488 }
00:51:11.193 info host starting host: {"extensionFolder":"/Users/liuyongtong/.vscode/extensions/wallabyjs.console-ninja-1.0.329","runtimeHookFile":"/Users/liuyongtong/.vscode/extensions/wallabyjs.console-ninja-1.0.329/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/Users/liuyongtong/.vscode/extensions/wallabyjs.console-ninja-1.0.329/out/runtimeHook/errorHandler.js","networkLoggingHandlerFile":"/Users/liuyongtong/.vscode/extensions/wallabyjs.console-ninja-1.0.329/out/runtimeHook/networkLoggingHandler.js","filesToInstrument":[{"path":"/volumes/t7/a/test/index.js","reason":"search"},{"path":"/Volumes/T7/a/test/index.js","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","dateTimeDisplayMode":"Absolute","installBinToPath":false,"openLinksInEditor":true,"maxLogViewerEntries":15000,"showWelcomeMessageInTools":true,"fontSize":10,"autoClearLogViewerOnFileChanges":true,"outputMode":"Beside File","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":false,"toolsToAutoPatch":["vite","angular","jest","webpack","next.js","nest.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro","live-server-extension","live-preview-extension"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false,"predictiveLoggingEnabled":false,"allowConsoleLogToTriggerPredictions":false,"showNetworkRequests":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","liuyongtongde-MacBook-Pro.local","192.168.0.18"],"host":"127.0.0.1","forcedStart":true,"startTime":1720759870761}
00:51:11.216 info host starting tools discovery and integration
00:51:11.222 info host looking for tools to patch
00:51:11.265 info host found 0 tool file(s) to patch
00:51:11.266 info host completed tools discovery and integration
00:51:11.269 ERR! host uncaught exception: No clients connected
00:51:11.329 info host worker Starting Host Worker...
```

**Comment by aprilllllllll** [comment]
![Screen Shot 2024-07-12 at 1 48 46 AM](https://github.com/user-attachments/assets/9b741cb8-f211-4ff3-a3b8-8edf6ea09c51)
On UNIX-based systems (e.g. MacOS, Linux) you may [source](https://ss64.com/bash/source.html) the console-ninja command for a terminal session. After that point, any commands you run in that terminal session will automatically be started with console-ninja. For example:

source console-ninja
node app1.js
node app2.js
If you manually manage your shell scripts then you may want to disable the automatic PATH appending behavior. The console-ninja.installBinToPath VS Code setting which is set to true by default allows to disable the behavior.

I did these step still have same issue

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. If you're still having a problem, please reply to [this message](https://github.com/wallabyjs/console-ninja/issues/316#issuecomment-2226736923) and we will re-open the issue.

**Comment by ilearnio** [comment]
@smcenlly

**Comment by smcenlly** [comment]
@ilearnio - Please uninstall the package `npm uninstall -g console-ninja` and follow [the instruction](https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#universal-node-applications) from the docs.

We haven't yet checked support for Antigravity IDE. Could you please check if it's working for you when using VS Code? This will allow us to isolate whether it's a problem with your project or with your editor.
