### ISSUE TITLE
Escape key not working on a multi cursor selection

### ISSUE THREAD

**Issue by onattech** [wallabyjs/console-ninja#32]
![image](https://user-images.githubusercontent.com/53895969/206764539-e6abf69b-8d5c-41c4-abbe-1015546dd18a.png)

### How to reproduce the issue
1. Select multi line by clicking ctrl + alt + down arrow.
2. Hit Esc key on the keyboard.

Instead of deselecting the lines like it should, it displays a message "(Escape) was pressed. Waiting for second key of chord..."
If I disable the extension for the workspace, Esc key works as usual.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in Console Ninja `v0.0.26`.

**Comment by onattech** [comment]
You're welcome. Thank you for making such a great app.
