### ISSUE TITLE
Using Pinia in Vue3

### ISSUE THREAD

**Issue by Gxc2xn** [wallabyjs/console-ninja#323]
### What happened?

I was expecting X to happen but instead Z happened.

### Version

1.0.333

### CLI command to start your dev tool

vite

### Steps to reproduce (or sample repo)

Pinia uses Composing Stores https://pinia.vuejs.org/cookbook/composing-stores.html, and printing the repository will report the following error:
![image](https://github.com/user-attachments/assets/17d6464d-daef-4d64-83d6-efec1fb480a5)

### Log output

```shell
13:47:38.620 info host client disconnected: runtimeHook 1001
13:47:38.620 info host client disconnected: runtimeHook
13:47:38.620 info host client disconnected: runtimeHook 1001
13:47:38.620 info host client disconnected: runtimeHook
13:47:38.621 info host client disconnected: runtimeHook 1001
13:47:38.621 info host client disconnected: runtimeHook
13:47:38.703 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 60113 }
13:47:38.717 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 60113 }
13:47:39.072 info host client connected: runtimeHook { address: '127.0.0.1', family: 'IPv4', port: 60113 }
```

**Comment by smcenlly** [comment]
We will need you to provide some additional detail to understand your issue.

It looks like there are some console warnings in your browser dev tools. We're assuming that they don't appear when not using Console Ninja? Do they cause any downstream errors that cause your application to fail?

Can you please provide us with a sample repo that has your problem, and provide more details of your exact problem? For example:

* Is your application not working when using Console Ninja, or
* Is Console Ninja not working, but your application still works,
* etc.

**Comment by Gxc2xn** [comment]
使用Console Ninja打印Pinia就会出现警告，Console Ninja和应用都正常工作。



---Original---
From: "Simon ***@***.***&gt;
Date: Wed, Jul 31, 2024 06:33 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wallabyjs/console-ninja] Using Pinia in Vue3 (Issue #323)




 
We will need you to provide some additional detail to understand your issue.
 
It looks like there are some console warnings in your browser dev tools. We're assuming that they don't appear when not using Console Ninja? Do they cause any downstream errors that cause your application to fail?
 
Can you please provide us with a sample repo that has your problem, and provide more details of your exact problem? For example:
  
Is your application not working when using Console Ninja, or
 
Is Console Ninja not working, but your application still works,
 
etc.

**Comment by smcenlly** [comment]
Can you please provide us with a sample repo and steps to reproduce so that we can see the warnings for ourselves?

**Comment by Gxc2xn** [comment]
在vue3中使用pinia，并打印pinia中的store就会警告。



---Original---
From: "Simon ***@***.***&gt;
Date: Wed, Jul 31, 2024 06:42 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wallabyjs/console-ninja] Using Pinia in Vue3 (Issue #323)




 
Can you please provide us with a sample repo and steps to reproduce so that we can see the warnings for ourselves?

**Comment by smcenlly** [comment]
Unfortunately if you are unable to provide a sample repo and steps to reproduce, we will not be able to help you with this issue.
