### ISSUE TITLE
[Feature]: Enhance Console ninja's allowed hosts to accept wildcards

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/console-ninja#325]
### Describe the feature you'd like.

I'd like to be able to add all the devices on my local network to console ninja's allowed hosts. For example: would it be possible to support adding an entire IP range like 192.168.*?

**Comment by omerson-cruz** [comment]
Hello I also would like to have this kind of support 
For example, be able to wildcard a subdomain

e.g. 
***.mydomain.com**

**Comment by smcenlly** [comment]
We have added support for wildcards as a **PRO feature**.

The `console-ninja.allowedHosts` setting (**with PRO**) now supports the use of `*` and `?` for wildcard matching (e.g. `*.example.com`), and regular expressions (e.g. `/^.*\\.example\\.com$/`).

**Comment by omerson-cruz** [comment]
Cool thank you so much for this. Kudos the Wallaby team as always!
