### ISSUE TITLE
Crash With latest version of vscode

### ISSUE THREAD

**Issue by DanielCArce** [wallabyjs/console-ninja#328]
Type: <b>Bug</b>

Update vscode to last version.

Extension version: 1.0.337
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz (2 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.84GB (1.22GB free)|
|Process Argv|--crash-reporter-id 6d99cf29-7c4c-40ed-be67-8976b81b3081|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-t:31106322

```

</details>

**Comment by smcenlly** [comment]
We're using the same version of VS Code and Console Ninja and it's working for us.

Can you please try closing all VS Code instances and then re-open and see if you're still having the problem?

There's no actual error information provided in your bug report. Can you please provide a screenshot of the error that you're seeing to provide more context?

**Comment by smcenlly** [comment]
@mmaazkhanhere - it looks like you have a different problem. I assume Console Ninja is not crashing for you? To troubleshoot your problem, we'll require some additional information. Could you please [create a new issue](https://github.com/wallabyjs/console-ninja/issues/new?assignees=&labels=bug%2Crequires+triage&projects=&template=bug.yml&title=%5BBug%5D%3A+) and provide the details requested in the issue template?

**Comment by DanielCArce** [comment]
I try all and with 1.92.0 of vscode doesn't work in windows, probably could be some of how work now with windows, because with vs 1.91.1 work so sweet.

**Comment by smcenlly** [comment]
@DanielCArce - we've tried Version 1.92.0 and it's working for us (see version details below from Help->About).

```
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621
```

Are you receiving an actual error? Could you please provide a screenshot so we can understand what's going on? Could you also please check the [Windows Event Viewer](https://learn.microsoft.com/en-us/shows/inside/event-viewer) to see if there's additional details about the error?

Also wondering if this is related to your project, if you try a different project, does it work for you?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back.
