### ISSUE TITLE
rg process spam

### ISSUE THREAD

**Issue by Pra3t0r5** [wallabyjs/console-ninja#329]
Type: <b>Bug</b>

It is spamming a process that draws too much power

Extension version: 1.0.337
VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|54, 56, 36|
|Memory (System)|24.00GB (1.66GB free)|
|Process Argv|--crash-reporter-id a6138847-bcb1-4857-a057-f36835bf207f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
wkspc-onlycs-c:31106320

```

</details>

**Comment by smcenlly** [comment]
Console Ninja uses VS Code's [ripgrep](https://github.com/BurntSushi/ripgrep) (i.e. rg process) to scan your project for `console.log` statements when it is not paused and your project first opens.

We haven't previously seen an issue with this, but I guess if you have a lot of files, perhaps this is causing a problem. Can you please run the following command from the command-line for the root of the folder you have opened in VS Code and provide us with the result:

```
find . -type f | wc -l
```

You said:

> It is spamming a process that draws too much power

Can you please provide us with a screenshot of the error message so we understand where this is coming from?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back.
