### ISSUE TITLE
[Feature]: Allow wildcard in the host subdomain

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#331]
### Describe the feature you'd like.

I'm not sure if this is already supported but currently I'm testing a website 
with multiple subdomain. (I'm testing it locally) 
like for example *.mydomain.com

Could you please add this kind of feature? 

Thank you

**Comment by smcenlly** [comment]
Closing as a duplicate of https://github.com/wallabyjs/console-ninja/issues/325#issuecomment-2261790921
