### ISSUE TITLE
[Bug]: vscode extension not working with node --inspect=9229 option

### ISSUE THREAD

**Issue by davidsantiagobillin** [wallabyjs/console-ninja#338]
### What happened?

Hi, the extension does not work for me if I execute my node app with option --inspect=9229 to ability debuggin.
If I remove --inspect option the extension works normally. What could be happening? Thanks.

### Version

1.0.357

### CLI command to start your dev tool

source console-ninja
node -r ts-node/register -r tsconfig-paths/register --inspect=9229 ./index.ts
// if I remove --inspect=9229 the extension works 
node -r ts-node/register -r tsconfig-paths/register ./index.ts

### Steps to reproduce (or sample repo)

node -r ts-node/register -r tsconfig-paths/register --inspect=9229 ./index.ts

### Log output

```shell
22:50:47.668 info host Host's startup and patch time: 1168 ms
22:50:47.668 info host completed tools discovery and integration
22:50:47.701 ERR! host uncaught exception: No clients connected
22:51:06.286 ERR! host uncaught exception: No clients connected
22:51:15.768 ERR! host uncaught exception: No clients connected
```

**Comment by smcenlly** [comment]
Thank you for reaching out. The behavior you're encountering is expected when using the `--inspect` flag for debugging. At this time, Console Ninja is not designed to work concurrently with the Node.js debugger.
