### ISSUE TITLE
 Console Ninja is ⌛ waiting for webpack, and jest to start. 

### ISSUE THREAD

**Issue by TafseerMD** [wallabyjs/console-ninja#34]
Console Ninja has successfully integrated with webpack, and jest found in your project dependencies, but has not connected to a running instance of it yet.
Can i get a fix for this ?

**Comment by ArtemGovorov** [comment]
> Can i get a fix for this ?

The status is not an indication of any problem. Console Ninja is waiting until you start webpack or jest in the project from CLI, and start using them. Please try starting your app/tests, add console.log to your code, run it and see if the status changes.

**Comment by TafseerMD** [comment]
Tried this but it,s not working

**Comment by ArtemGovorov** [comment]
Can you please: 
- create a sample Github repository demonstrating the issue, we'll need it to investigate.
- share the extension trace.log file (located at `~/.console-ninja/trace.log`).

**Comment by TafseerMD** [comment]
Is there a way i can send you the trace.log file ?

**Comment by ArtemGovorov** [comment]
Yes, you may either attach it to the issue, or email it to us to hello@wallabyjs.com. Please not that we also need a sample repo to start investigating the issue.

**Comment by ArtemGovorov** [comment]
If you are using a monorepo, please try the latest version of the extension to see if it fixes things for you.

**Comment by TafseerMD** [comment]
I've tried the latest version and it's fixed automatically , thanks :). One of my favourite extension now :).

**Comment by Antjrobles** [comment]
Hi! Same problem here. I'm using latest version, but still getting the same message: "Console Ninja is ⌛ waiting for webpack, and jest to start".  Thanks in advance.

**Comment by smcenlly** [comment]
@Antjrobles - please create a [new bug report](https://github.com/wallabyjs/console-ninja/issues/new?assignees=&labels=bug%2Crequires+triage&template=bug.yml&title=%5BBug%5D%3A+) and provide us with a reproduceable sample.
