### ISSUE TITLE
[Bug]: Can't found NextJS dependencies

### ISSUE THREAD

**Issue by xdanrj** [wallabyjs/console-ninja#340]
### What happened?

![image](https://github.com/user-attachments/assets/f41d8e32-a313-43a7-a8fd-58e4c6282b90)

### Version

v1.0.359

### CLI command to start your dev tool

npm run dev 
` "next dev -H 192.168.1.65" `

### Steps to reproduce (or sample repo)

I was using the extension normally yesterday, today I just run the project but Console Ninja can't detect the NextJS at all.

### My dependencies

   ```
 "@nextui-org/react": "^2.4.6",
    "axios": "^1.7.3",
    "dayjs": "^1.11.12",
    "flowbite-react": "^0.10.1",
    "jose": "^5.6.3",
    "lodash": "^4.17.21",
    "mongodb": "^6.8.0",
    "next": "^14.2.12",
    "next-auth": "^5.0.0-beta.20",
    "next-themes": "^0.3.0",
    "react": "^18",
    "react-dom": "^18",
    "react-toastify": "^10.0.5"
```

### Log output

```shell
14:11:27.633 info extension stopping host
14:11:28.044 info host ------------ starting ------------
14:11:28.080 ERR! host uncaught exception: listen EACCES: permission denied 127.0.0.1:62079
14:11:28.324 info host worker Starting Host Worker...
14:11:28.487 info extension host process output: port:[62079]
14:11:28.487 info extension 
14:11:28.553 ERR! extension connection error: connect ECONNREFUSED 127.0.0.1:62079
14:11:28.553 info extension client disconnected: 1006 
14:11:29.014 ERR! extension WebSocket failed to become ready to send messages WebSocket is not in a state to send messages
```

**Comment by mburnell** [comment]
`next ^14.2.12` isn't yet supported by Console Ninja Community. You should be receiving a message explaining this, along with an estimated date that support for this version of `next` will become available. This isn't what you're seeing in your logs, though, so it looks like something else might be going wrong along the way. We haven't been able to reproduce your error locally with similar configuration. You mentioned Ninja was working for you yesterday; we're assuming this was with an older version of `next`. If you revert to this version, does your project work again?

For reference, with 14.2.12, you should be seeing something like this:

<img width="713" alt="image" src="https://github.com/user-attachments/assets/8ea03711-fa50-410a-b2eb-6f771ebd5c83">

**Comment by xdanrj** [comment]
> `next ^14.2.12` isn't yet supported by Console Ninja Community. You should be receiving a message explaining this, along with an estimated date that support for this version of `next` will become available. This isn't what you're seeing in your logs, though, so it looks like something else might be going wrong along the way. We haven't been able to reproduce your error locally with similar configuration. You mentioned Ninja was working for you yesterday; we're assuming this was with an older version of `next`. If you revert to this version, does your project work again?
> 
> For reference, with 14.2.12, you should be seeing something like this:
> 


And what is the latest version of NextJS supported?

**Comment by mburnell** [comment]
`next 14.2.5` is the latest version currently supported by Console Ninja Community.
