### ISSUE TITLE
[Bug]: ninja inline logs dosen't work

### ISSUE THREAD

**Issue by OB-111** [wallabyjs/console-ninja#344]
### What happened?

I was expecting  to see ninja icon after I activated successfuly the pro extension  but its dosent work and I cannot see any logs or console.log
v1.0.360 

![Screenshot 2024-09-30 at 15 49 06](https://github.com/user-attachments/assets/f6bf93c6-ef1a-46a3-ba1b-50296beaf1ac)
![Screenshot 2024-09-30 at 15 47 43](https://github.com/user-attachments/assets/16c9bf6e-84ed-40d4-9eb6-5f390f2973c6)

### Version

v1.0.360

### CLI command to start your dev tool

simple live server

### Steps to reproduce (or sample repo)

none

### Log output

```shell
none
```

**Comment by smcenlly** [comment]
You said, `simple live server`, I assume by this, you mean the [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) VS Code extension? If so, please note ([mentioned here](https://github.com/wallabyjs/console-ninja?tab=readme-ov-file#supported-technologies)) that by default this is disabled, and you will need to turn it on in the Console Ninja settings.

You will need to ensure that Console Ninja is started for your project before you launch Live Server. You will also need to click on the button of your web page before you see the logs for it.

You mention that there is no `Log output`. In the issue template, we asked for the contents from the `~/.console-ninja/trace.log` file in your user home directory. Even if you have no Console Ninja output, we would still expect to see log content written to the trace file. Can you please check this again? If it does have output, please try to start Live Server again, and then provide us with the `trace.log` contents.

If you're still having problems, can you also please provide us with the `index.html`, and `script.js` contents along with the exact steps you're taking to launch and use the page?

**Comment by OB-111** [comment]
hey 
thank you for your answer
I tried all in the order you said and its not work...
I do not have trace.log file in my directory 
here is the zip file :
[ninja.zip](https://github.com/user-attachments/files/17200414/ninja.zip)

**Comment by smcenlly** [comment]
> I do not have trace.log file in my directory

Did you look for the file in your project folder or within the hidden `.console-ninja` folder in your home directory?

> here is the zip file :

Thanks for the sample. We've tried it and it's working for us. Here are the exact steps we took:

1. Ensure that [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) is enabled for Console Ninja via the `console-ninja.toolsToEnableSupportAutomaticallyFor` setting:
![Untitled 2](https://github.com/user-attachments/assets/8b7be380-d03d-48aa-a78d-731b7671feef)

2. Restart VS Code if the setting wasn't previously enabled

3. After loading your project, if Console Ninja is paused (see the Console Ninja status icon on the bottom right of the screen), then click on the status icon and select `Start Console Ninja`:
<img width="764" alt="image" src="https://github.com/user-attachments/assets/62c806ec-de72-4a56-b260-e7784ae29538">

4. Navigate to your `index.html` file and run the Live Server command, `Live Server: Open with Live Server`:
<img width="374" alt="image" src="https://github.com/user-attachments/assets/cf1d63b5-6038-4303-a1e1-1a48c4edce2e">

5. Click on the `Click Me` button

6. Go back for VS Code and open your `script.js` file, you should see the logged value next to your code, and in the `Console Output` viewer:

<img width="1219" alt="image" src="https://github.com/user-attachments/assets/10da6f41-0873-4a2c-95df-1999cc1b5240">

--

If it's still not working for you and you don't have a `trace.log` file in the hidden `.console-ninja` folder in your home directory, can you please open the VS Code developer tools using the `Developer: Toggle Developer Tools` command and check the **console** for errors?

**Comment by smcenlly** [comment]
We're assuming our last reply helped you get this working and are closing the issue. If you're still having problems, please let us know.

**Comment by OB-111** [comment]
its still not worked..
<img width="1107" alt="Screenshot 2024-10-04 at 10 45 42" src="https://github.com/user-attachments/assets/646e6b21-42b9-440f-9e26-3e3cecd9dfc1">

**Comment by smcenlly** [comment]
Could you please provide the details requested in our last reply so that we can help you?

> If it's still not working for you and you don't have a `trace.log` file in the hidden `.console-ninja` folder in your home directory, can you please open the VS Code developer tools using the `Developer: Toggle Developer Tools` command and check the **console** for errors?

**Comment by OB-111** [comment]
![Uploading Screenshot 2024-10-06 at 8.48.29.png…]()

**Comment by OB-111** [comment]
@smcenlly ??

**Comment by smcenlly** [comment]
Sorry for the back and forth, we're quite confused about there being no `trace.log` file and yet you're still seeing the Console Ninja user interface.

Can you please run this from the command-line and provide us with the output?

```
cat ~/.console-ninja/trace.log
```

**Comment by smcenlly** [comment]
Thanks for providing the `~/.console-ninja/trace.log` file contents.

Your log file shows that you have enabled the `console-ninja.output.showLogsFromLogPointsOnly` setting:

<img width="932" alt="image" src="https://github.com/user-attachments/assets/e19d4d30-1dd0-44b7-b00d-1ccb8345df8a">

As per the setting description, when enabled, `console.log`, `console.trace`, `console.time`, `console.warn`, `console.info` and `console.debug` will not be displayed.

---

Based on the rest of your trace file, you should be able to restore the setting to it's default (unchecked), and it should work for you.
