### ISSUE TITLE
[Bug]: Code in injected in production when running `astro check`

### ISSUE THREAD

**Issue by essential-randomness** [wallabyjs/console-ninja#345]
### What happened?

When building my website I run the `astro check` command, as is recommended to get type errors (https://docs.astro.build/en/guides/typescript/#type-checking). At that time I get an error because console ninja is injecting code in my `<script type="module">` tags.

If I disable Console Ninja the code compiles. It also compiles if I run `NODE_ENV=prod astro check` instead, or just run `astro build`.

You probably want to disable Console Ninja also in `astro check` mode.

----
Aside comment since I'm here: regarding your README, I don't think it's unlikely to run builds directly on a local dev computer. I need to build these files as part of my development pipeline so I can work on other code that further processes them. While the final build may be done in a different environment or with different tooling, running the build on the dev machine it's part of the correct flow for local development. It's also often necessary to run local builds to debug CI errors. I would suggest rephrasing that section :)

### Version

v1.0.361

### CLI command to start your dev tool

`npm run build`, which then runs `astro check && tsc --noEmit && astro build"`

### Steps to reproduce (or sample repo)

1) Add a  `<script type="module">` tag to an astro file, with some content inside
2) Try running `astro check`

### Log output

```shell
I don't have it right now
```

**Comment by ArtemGovorov** [comment]
In case if you were referring to the README section I have mentioned above, I have pushed the change to make "and" between "building" and "deploy" to look more prominent:
<img width="1142" alt="Screenshot 2024-10-07 at 8 29 10 PM" src="https://github.com/user-attachments/assets/1179f7a7-5594-49b9-ae0c-7a628605ce27">
