### ISSUE TITLE
[Bug]: Vite v5.4.10 support for Community Edition

### ISSUE THREAD

**Issue by DevOBR** [wallabyjs/console-ninja#352]
### What happened?

I have my project in **Reac** with **Vite**  and I installed Community Edition of Console Ninja, and I am getting the next issue from the console after I run the command `npm run dev`: 

`vite v5.4.10 is not yet supported in the Community edition of Console Ninja.`

![image](https://github.com/user-attachments/assets/b0492772-3014-4c9a-8c69-41f70a959752)

### Version

v1.0.366

### CLI command to start your dev tool

npm run dev

### Steps to reproduce (or sample repo)

I have my project in **Reac** with **Vite**  and I installed Community Edition of Console Ninja, and I am getting the next issue from the console after I run the command `npm run dev`: 

### Log output

```shell
✘ vite v5.4.10 is not yet supported in the Community edition of Console Ninja.
We are working hard on it for you https://tinyurl.com/3h9mtwra.
```

**Comment by smcenlly** [comment]
The message about Vite v5.4.10 not being supported in the Community Edition is correct and expected. Community Edition updates typically follow new releases by about two months to ensure stability. For faster updates, the Pro Edition supports new versions within 1-2 days.
