### ISSUE TITLE
[Bug]: I removed the extension but still runs everytime I launch a server?

### ISSUE THREAD

**Issue by muchisx** [wallabyjs/console-ninja#358]
### What happened?

I use Remix and not sure if it's connected to it, or if it happens to any framework, the extension has been removed and my pc restarted multiple times.

Windows 11

![image](https://github.com/user-attachments/assets/6a0d85b9-4896-4fd5-9b9f-9aa2e202a96b)

![image](https://github.com/user-attachments/assets/b159c675-d2b1-49ef-93aa-6c0e274d0c81)

### Version

none

### CLI command to start your dev tool

npm run dev

### Steps to reproduce (or sample repo)

install the extension,
use remix,
uninstall the extension,
still shows up

### Log output

```shell
n/a
```

**Comment by smcenlly** [comment]
Can you please try deleting your `node_modules` and reinstalling them? It should fix the problem.
