### ISSUE TITLE
[Bug]: Console Ninja misrecognized my nextjs version after a revert from 15 to 14

### ISSUE THREAD

**Issue by banuni** [wallabyjs/console-ninja#364]
### What happened?

NOTE: I AM using nextjs version 14
After upgrading to next15, and then back to 14, Console Ninja still thinks I'm on 15 and refuses to load
![image](https://github.com/user-attachments/assets/07f149f4-da87-4564-b490-540bf27dfbbf)

### Version

v1.0.376

### CLI command to start your dev tool

yarn workspace <my-worksapce> ESM_EXTERNALS=true next dev

### Steps to reproduce (or sample repo)

1.yarn up next@15
...make app work with 15
2. yarn up next@^14
3. start the application

### Log output

```shell
...
✘ next.js v15.1.0 is not yet supported in the Community edition of Console Ninja.
We are working hard on it for you https://tinyurl.com/3h9mtwra.

Estimated release dates:
  - Community users: around 10th February, 2025 (subject to team availability)
  - PRO users:       priority access is available now

info - Using cdn 'undefined' on phase 'phase-development-server'
  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000
...
```

**Comment by smcenlly** [comment]
Can you please try the following:

1. Pause Console Ninja with `Console Ninja: Pause`
2. Restart Console Ninja with `Console Ninja: Start`

If that doesn't fix your problem then you must still have some next@15 dependencies installed in your project. You may try deleting your dependencies folder, `yarn.lock` file and then try reinstalling your dependencies to fix the problem.

**Comment by banuni** [comment]
ok, apparently the culprit was a leftover `eslint-config-next@^15`
after removing it things seem to work fine :)
