### ISSUE TITLE
[Feature request] Add the //? syntax to log

### ISSUE THREAD

**Issue by Noriller** [wallabyjs/console-ninja#43]
I have both quokka and wallaby and I feel it's missing being able to use the `//?` to console the values.

Maybe you could add this as a bonus to people who have a license for either quokka and/or wallaby?

I'm really enjoying the extension so far. Thank you!

**Comment by smcenlly** [comment]
At this point, we don't have any intention of introducing something like `Live Comments` for Console Ninja as if anything, we want to limit changing code to see runtime values.

We have recently released our [`Logpoints` feature](https://github.com/wallabyjs/console-ninja#pro-features) which allows you to log the value of any expression in your code, without modifying your code, by simply placing a VS Code breakpoint in your code. Please read the docs for more information.

I think Logpoints are a superiour version of what you're asking for, so I'm going to close this issue.
