### ISSUE TITLE
Breaks Angular CLI ng build command. Index html generation failed

### ISSUE THREAD

**Issue by digitalcraftco** [wallabyjs/console-ninja#45]
When Console Ninja is enabled it's causing the index.html generation step to fail. I believe it's webpack related but not sure. If you disable plugin the build works as expected.

`ng build <app-name>`

```
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
(intermediate value).default is not a constructor

Console Ninja v0.0.31
Angular v15.0.2

**Comment by smcenlly** [comment]
It appears to be working for us. Could you please try the steps below and let us know if it works for you?

We experimented with routing / stylesheet format but it worked with different settings for us.

1. `ng new my-angular-app-45`
2. ? Would you like to add Angular routing? `Yes`
3. ? Which stylesheet format would you like to use? `SCSS`
4. `cd my-angular-app-45`
5. `code .`
6. In VS Code integrated terminal `ng build my-angular-app-45`

---

If that works for you, could you please provide us with updated steps to reproduce the problem?

Could you also please provide us with:
* Your operating system and version
* Your `package.json`, and
* Your `package-lock.json`?
