### ISSUE TITLE
Does it work with nodejs express, fastify ...?

### ISSUE THREAD

**Issue by haikyuu** [wallabyjs/console-ninja#47]
If so, how to enable it?

**Comment by ArtemGovorov** [comment]
There's a plan to make it work with application launched directly as `node file_name.js`.

**Comment by patroza** [comment]
> There's a plan to make it work with application launched directly as `node file_name.js`.

this would be great. having it all centrally integrated with the editor is a cool unified experience.

**Comment by jaydeepkarena** [comment]
Yes, i am looking for the same.

**Comment by MateoCerquetella** [comment]
Same for me!

**Comment by omerson-cruz** [comment]
Yes, this would be great feature too :)

**Comment by patroza** [comment]
> There's a plan to make it work with application launched directly as node file_name.js.

how's that going @ArtemGovorov ? we could really use this atm.

**Comment by ArtemGovorov** [comment]
@patroza  We are working on it, however no ETA to share yet.

**Comment by suryarajendhran** [comment]
Adding a comment here so the team knows that there's a lot of demand for this feature!

**Comment by NikGovorov** [comment]
Hi guys,

Today, we are happy to announce the release of support for `node app.js`-like workflows. Please refer to [Universal Node applications](https://github.com/wallabyjs/console-ninja#universal-node-applications) section of our docs for more information.

**Comment by tarwich** [comment]
Apologies for the necro, but I tried using this a little last week, and couldn't get it to work. 

```sh
❯ console-ninja node test.js
fish: Unknown command: console-ninja
```

```sh
bash-3.2$ console-ninja node test.js
bash: console-ninja: command not found
```

I've tried 
- Running as a task
- Running as a shell command
- Running `console-ninja`
- Running `/Users/.../.vscode/extensions/wallabyjs.console-ninja-0.0.91/out/shell/console-ninja`
- Uninstalling and reinstalling
- Resetting all settings

Can't figure out how this is supposed to be working. 

```yaml
node: 14.21.2
Operating System:
  darwin: 22.3.0
  arch: x64
```

**Comment by patroza** [comment]
so the extension in vscode has installed `console-ninja` to my bin:
`~/.local/bin/console-ninja`

**Comment by tarwich** [comment]
Thanks @patroza that's definitely what I suspected. I don't have that file. 

```sh
❯ ls -la1 ~/.local
./
../
share/
state/
```

I've uninstalled, rebooted, installed the extension. Will continue to google. If you're comfortable sharing, what's the contents of your `~/.localbin/console-ninja` file? I have this:

```sh
❯ cat ~/.vscode/extensions/wallabyjs.console-ninja-0.0.91/out/shell/console-ninja
#!/bin/sh
export NODE_OPTIONS='--no-warnings --loader "<REPLACE>"';
$@
```

```sh
❯ ls -l1 ~/.vscode/**/console-ninja
~/.vscode/extensions/wallabyjs.console-ninja-0.0.91/out/shell/console-ninja
```

**Comment by tarwich** [comment]
Found something useful in the log...

```
info host creating /Users/.../.console-ninja/.bin
info host installing /Users/.../.console-ninja/.bin/loader.js
info host installing /Users/.../.console-ninja/.bin/console-ninja
info host installing /usr/local/bin/console-ninja
ERR! host failed to create symbolic link EACCES: permission denied, symlink '/Users/.../.console-ninja/.bin/console-ninja' -> '/usr/local/bin/console-ninja'
```

Continuing looking for data...

```
❯ ls -la1 ~/.console-ninja/.bin
./
../
console-ninja*
loader.js
```

<details><summary>Experiment 1 (fail)</summary>
<p>

Trying this:

```
 ~/.console-ninja/.bin/console-ninja npm run dev
```

didn't work.

</p>
</details> 

Let console ninja make the .local/bin stuff...

```
mkdir -p ~/.local/bin
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.profile
```

Restart vscode...

```
❯ ls -la1 ~/.local/bin
./
../
console-ninja@
```

Ok... better...

<details><summary>Experiment 2 (fail)</summary>
<p>

**test.js**
```js
console.log('test');
new Promise(resolve => { setTimeout(resolve, 5000); })
.then(() => console.log('done'));
```

```
❯ console-ninja node test.js
test
done
```

![image](https://user-images.githubusercontent.com/334149/228100573-0c35474d-c229-4f17-ade3-78aad7275fac.png)

</p>
</details> 

Still not working, but progress was made

**Comment by NikGovorov** [comment]
Thanks for sharing the details, we'll change the installation process to include shell profile scripts change (prepending to PATH variables) and mention the min version of nodejs in our docs.

**Comment by tarwich** [comment]
Thanks for the response! Updating the docs would help! 

I don't like tools to touch my .profile without permission. Plus I am using fishshell, so it wouldn't have helped. I switched to bash for troubleshooting purposes. It would be nice if this were a setting, or something (even if it were defaulted to true). Perhaps instead of a setting, a command? I'll let y'all worry about that. Just wanted to weigh in. 

Love you guys!
