### ISSUE TITLE
Causes NextJS development build to crash

### ISSUE THREAD

**Issue by jpwallace22** [wallabyjs/console-ninja#54]
## Operating details
```
Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
    Binaries:
      Node: 18.12.1
      npm: 8.19.2
      Yarn: 1.22.19
      pnpm: 6.11.0
    Relevant packages:
      next: 13.0.7-canary.4
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```
## Description 
When using `console.log()` top level within a react component it causes this error:
![Screen Shot 2022-12-15 at 11 19 56 AM](https://user-images.githubusercontent.com/93415734/207948496-6bf8b072-6451-4e95-9169-2047f54ff9ad.png)

When used within the `<JSX>` return, I get the following:
![Screen Shot 2022-12-15 at 11 25 08 AM](https://user-images.githubusercontent.com/93415734/207949312-ebcb787a-19f0-4651-84a3-fff2ba4b55b8.png)

**Comment by ArtemGovorov** [comment]
Can you please share what version of the extension is/was used to reproduce the errors?

**Comment by jpwallace22** [comment]
Sorry, I was forced to uninstall it and do not remember the version. @ArtemGovorov

**Comment by smcenlly** [comment]
With other fixes we have made, we believe that this issue is now resolved. If you're still experiencing the issue, please let us know and we will re-open.
