### ISSUE TITLE
(Vue/Nuxt) Syntax Error: Identifier 'oo_oo' has already been declared.

### ISSUE THREAD

**Issue by baptistebriel** [wallabyjs/console-ninja#56]
Fun tool! I'm working with Nuxt.js and I'm getting an error that `oo_oo` has been already declared.

<img width="1117" alt="Screenshot 2022-12-16 at 12 18 32" src="https://user-images.githubusercontent.com/2464663/208087136-d816d1cf-b06c-472b-ba71-a4993f560806.png">

**Comment by ArtemGovorov** [comment]
Can you please try again with the latest version of the tool as we have made some changes to the Nuxt integration that may have affected the issue?

If it's still not working, can you please 
- share your `./pages/index.vue` file,
- share your `~/.console-ninja/trace.log` file.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you're still having problems, please ensure you are using the latest version and then provide teh details requested above.
