### ISSUE TITLE
Support for ts-node and ts-node-dev

### ISSUE THREAD

**Issue by Avivbens** [wallabyjs/console-ninja#60]
Is there any chance to support console-ninja extension when running a typescript project via ts-node?

Currently, the supported options are only frameworks that create a dist / JS projects.

**Comment by smcenlly** [comment]
Out of interest, do you install `ts-node` globally or within your project? 

Console Ninja currently only works with project-level dependencies so if you're running with a globally installed `ts-node`, it might be a larger change for us.

**Comment by Avivbens** [comment]
Well, it does install on the global level, but as project devDependencies as well

**Comment by Avivbens** [comment]
<img width="609" alt="Screenshot 2022-12-22 at 14 09 07" src="https://user-images.githubusercontent.com/77183871/209131538-91facf32-6e22-45f6-b9c6-547e262bdad9.png">
Here is the message I get
