### ISSUE TITLE
ANSI escape codes are printed as-is

### ISSUE THREAD

**Issue by adri326** [wallabyjs/console-ninja#64]
The following piece of code should display `Hello world` next to the console log, but it instead prints it with the ANSI escape codes:

```
console.log(chalk.yellowBright('Hello world'));
```

## Expected:

```
console.log(chalk.yellowBright('Hello world'));    Hello world
```

## Actual:

```
console.log(chalk.yellowBright('Hello world'));    [93mHello world[39m
```

**Comment by smcenlly** [comment]
Interestingly, the problem doesn't occur when using Safari, but does occur when using Chrome.

**Comment by smcenlly** [comment]
We've updated Console Ninja to strip all ANSI escape codes from strings.

Please update to Console Ninja `v0.0.53`, it will fix your problem.
