### ISSUE TITLE
Doesn't work with Shopify CLI

### ISSUE THREAD

**Issue by hleon57** [wallabyjs/console-ninja#66]
### Describe the feature you'd like.

Hello Wallaby Team!

Will this have support for [Shopify CLI for Themes](https://shopify.dev/themes/tools/cli)? 

I've been hyped about this extension but doesn't work with Shopify CLI. Not sure if any configuration is needed or it's not supported it at the moment.

Thanks for the awesome work you've done!

**Comment by hleon57** [comment]
@smcenlly any plans to suppport Shopify CLI for this extension dying to use it but I work 100% with Shopify CLI. 

Thanks !

**Comment by smcenlly** [comment]
We're not familiar with `Shopify CLI`. Can you tell us a little more about it and how it works?

I saw from the docs it mentions you need a `development store` and there is also mention of authentication? I assume that this means that you're deploying to an external (non-local) server to see / test your theme?

If it's possible to run everything locally, if you're able to provide us with a sample repo and steps for running Shopify CLI locally, that would expedite our triage process so we can understand whether we can support Shopify CLI.

**Comment by hleon57** [comment]
Normally you download the CLI with the terminal it runs on a local environment, not sure what they are using for a live server locally. Nothing is pushed until you need a preview theme. So everything is run locally until you need to push. 

Github: https://github.com/Shopify/cli
Docs: https://shopify.dev/docs/themes/tools/cli

Thanks

**Comment by hleon57** [comment]
Hey @smcenlly, anything else you need me to research or something ? 

To try and make this to work haha

**Comment by smcenlly** [comment]
@hleon57 - as per my [comment above](https://github.com/wallabyjs/console-ninja/issues/66#issuecomment-1423392418):

> if you're able to provide us with a sample repo and steps for running Shopify CLI locally, that would expedite our triage process so we can understand whether we can support Shopify CLI.

It's quite easy for us to check an existing repo with clear step-by-step instructions for installing dependencies and starting a dev environmente to understand if we can add support for it. If we need to read through docs and try and learn the tech first, it takes us a bit longer and that also factors into how we prioritize other work.

**Comment by hleon57** [comment]
Sorry for the late response, I've just seen you've answered this.

Instalation (MacOS):
brew tap shopify/shopify
brew install shopify-cli

To start a dev envirnoment:
shopify theme dev --store=https://mystore.myshopify.com

I'm not 100% what does shopify-cli uses internally I can look if that helps

Thanks!

**Comment by hleon57** [comment]
@smcenlly Any updates? Thanks!

**Comment by smcenlly** [comment]
We spent an hour or so taking a look at the theme dev and it looks like it's hosted in Ruby for the development runtime instead of node.js, so right now it doesn't look like something we can easily add.

**Comment by hleon57** [comment]
@smcenlly Thanks for the update !
