### ISSUE TITLE
[Feature]:  pusblish the extention on open-vsx.org

### ISSUE THREAD

**Issue by abdelghanyMh** [wallabyjs/console-ninja#72]
### Describe the feature you'd like.

- Would it be possible to publish this extension on [open-vsx.org](https://open-vsx.org/) in addition to the VS Code Marketplace?
- The publishing process is documented in the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by smcenlly** [comment]
Unfortunately we cannot publish to the open vsx repository as publishing to the open vsx repository is only available for open-source projects ([see agreement here](https://www.eclipse.org/legal/ECA.php)).

To use Console Ninja in other editors you will need to download the extension from the Microsoft marketplace and then install from VSIX. For example, this is described in the [VS Codium docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace).
