### ISSUE TITLE
[Feature]: Solidjs Support

### ISSUE THREAD

**Issue by kevinseabourne** [wallabyjs/console-ninja#73]
### Describe the feature you'd like.

Just requesting support for Solidjs with Console Ninja ? 

Congrats on the launch of Console Ninja !

![75ijuz](https://user-images.githubusercontent.com/29522030/209504253-edd8d810-f4f4-4638-8b0e-ff2ad01ac343.jpeg)

**Comment by smcenlly** [comment]
We're not super-familiar with Solid.js but yesterday we followed the tutorial and created a new project and Console Ninja was working for us:

<img width="1868" alt="image" src="https://user-images.githubusercontent.com/2074089/217677653-e75c5475-f7f7-4bfb-8b89-7f2b131f9317.png">

---

If it's not working for you, can you please create a sample repo for us along with steps to install / reproduce it not working?

**Comment by kevinseabourne** [comment]
Awesome ! I updated my packages and it worked ! maybe that had something to do with it. Thanks for taking a look and everything to do with wallaby.js.

![download (2)](https://user-images.githubusercontent.com/29522030/217723237-74d30d95-90f0-49e5-95e7-b0508d9e7d1c.png)

**Comment by smcenlly** [comment]
Great to hear. We'll close this issue.
