### ISSUE TITLE
[Feature]: Quasar Support

### ISSUE THREAD

**Issue by YonatanCohavi** [wallabyjs/console-ninja#75]
### Describe the feature you'd like.

I would love to see support for [Quasar ](https://quasar.dev/). I thought it might work "out of the box" since quasar is running on vite, but Console Ninja gives the message "waiting for vite to start" even with the dev server running

**Comment by smcenlly** [comment]
Closing as this is already a feature request: https://github.com/wallabyjs/console-ninja/issues/39
