### ISSUE TITLE
[Feature]:  QT/QML javascript

### ISSUE THREAD

**Issue by alfredopons** [wallabyjs/console-ninja#76]
### Describe the feature you'd like.

Would it be possible to have support for QT/QML javascript?

**Comment by smcenlly** [comment]
We're not familiar with QT/QML. Could you please include links to the technology and include and a sample project that uses that technology along with steps to run it?

If QT/QML do not run in a JavaScript runtime (i.e. `node.js` or browser) then we are unlikely to be able to support in the short term.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Please reply with the information requested and we will re-open the issue.
