### ISSUE TITLE
[Feature]: color managment for output

### ISSUE THREAD

**Issue by Captain-Leftovers** [wallabyjs/console-ninja#78]
### Describe the feature you'd like.

I would love the ability to change the color of the log inside my editor from the extension
it matches many themes and it takes from the user experience
Love the extension keep the good work :)

**Comment by smcenlly** [comment]
Can you please provide a little more context on your feature request. 

By design, Console Ninja uses your VS Code theme colours. Is this not working for you? Perhaps you can provide a screenshot so we can understand if this is a bug vs. feature request?

**Comment by ArtemGovorov** [comment]
@smcenlly I think @Captain-Leftovers is referring to **inline** output colors for logs and errors, that are not using current theme and can not be changed at the moment.

**Comment by ArtemGovorov** [comment]
We have added configuration options to modify inline colors in the latest extension v0.0.56+.

<img width="737" alt="Screen Shot 2023-01-09 at 1 00 43 pm" src="https://user-images.githubusercontent.com/979966/211234598-1b01e5f2-e6a1-46ff-8fa2-3a423fc3ae63.png">
