### ISSUE TITLE
[Bug]:  Console Ninja not finding dependencies when specific project opened in monorepo

### ISSUE THREAD

**Issue by lstephensca** [wallabyjs/console-ninja#81]
### What happened?

I created a brand new vite + preact project inside a Monorepo (MonoRepo -> projects/project-a) where console ninja is not actively watching. I opened the project via terminal running "code projects/project-a" and had to manually start code ninja in vscode by clicking the icon in the lower right corner. Unfortunately, I get the following "error":

**Console ninja has scanned your project for dependencies, but has not found any tools that are supported**

If I open the monorepo from the root by "code ." and start the project via "yarn workspace project-a dev", console ninja will run just fine.

I went through the entire process described above in a new folder and console ninja ran perfectly when just the single project was opened in vscode. It seems to be an intermentent issue that doesnt always occur. 

### Version

0.0.54

### Steps to reproduce (or sample repo)

In terminal:

1.  mkdir Monorepo && cd Monorepo
2. yarn init
3. add workspaces to Monorepo package.json (projects/*)
4. mkdir projects && cd projects
5. yarn create vite (project-a) and then install dependencies
6.  (in Monorepo root) - code projects/project-a
7. yarn workspace project-a dev (start dev server)

### Log output

```shell
info host starting tools discovery and integration
info host looking for tools to patch
info host found 0 tool file(s) to patch
info host worker Starting Host Worker...
info host completed tools discovery and integration
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repro steps. 

The behaviour is described at https://github.com/wallabyjs/console-ninja/issues/36#issuecomment-1345455464:

> Right now, if the very root of the monorepo is opened in VS Code as project (and not an individual package), then running dev server in individual packages should work.

> It should also work if an individual package has all of its node modules inside its subfolder (and not hoisted).

> What doesn't work right now, is opening an individual package as a project in VS Code with no node modules installed in the individual package folder (but installed in parent/root directory for example).

You may subscribe to the https://github.com/wallabyjs/console-ninja/issues/36 issue to get an update when the scenario is supported.
