### ISSUE TITLE
Console ninja is injecting obfuscated javascript into published NPM modules

### ISSUE THREAD

**Issue by samdenty** [wallabyjs/console-ninja#82]
### What happened?

I opened a previous issue here https://github.com/wallabyjs/console-ninja/issues/70

Now i've found out that it's injecting mangled javascript into my npm modules before being published to the NPM registry. And they open websocket connections! Disabled the extension outright now

**Comment by samdenty** [comment]
No this is still an issue.

Console ninja is injecting javascript into libraries build outputs, before they're published to NPM.

So packages you publish end up containing obfuscated javascript which is a no-no for security. And they open websockets which could for example be used to establish a connection to a malicious server.

I highly recommend you don't modify any files to do with npm modules that are going to be published.

I also suggest that you don't obfuscate the runtime code, and it's not necessary

**Comment by ArtemGovorov** [comment]
> Console ninja is injecting javascript into libraries build outputs, before they're published to NPM.
> I highly recommend you don't modify any files to do with npm modules that are going to be published.

Can you please tell us a bit more about how exactly your project is structured so we can reproduce the issue? If it's an OSS repo, or something that you can share, please paste a link to the repo. If we can capture the "npm modules that are going to be published" user intent, we can surely skip the code injection.

**Comment by samdenty** [comment]
it's not oss unfortunately. But the steps to reproduce:

1. Have console ninja installed
2. Have a package.json with a `bin` field (maybe it's also an issue with `files` field)
3. Build library
4. Files are modified by console-ninja, and are published to NPM with `yarn publish`

Maybe you could ignore bin/all files listed in `files`.

You could patch NPM/Yarn (or add a `prepack/prepublish/prepare` script in package.json) to restore the files upon publish

**Comment by ArtemGovorov** [comment]
@samdenty Thanks, can you please clarify a couple more things:

> Build library

How exactly the library is built? What tool is used to do it? Perhaps any special arguments/flags are passed (like some kind of prod flag or something)?

> Files are modified by console-ninja

I'm assuming those are files with `console.log(...)` inside them?

**Comment by samdenty** [comment]
Library is built with webpack without any flags aka default mode, yes it has console logs.

I still think regardless of build tooling, if it outputs to anything in files / bin you ignore it

**Comment by samdenty** [comment]
Library is built with webpack without any flags aka default mode, yes it has console logs.

I still think regardless of build tooling, if it outputs to anything in files / bin you ignore it

**Comment by ArtemGovorov** [comment]
So webpack in this project is used solely as a build tool, correct? Ie. you don't run it in the project other than for building the library? Also, is the build command located in the `package.json` `scripts`? If so, does it look like `"build": "webpack"`?

> I still think regardless of build tooling, if it outputs to anything in files / bin you ignore it

It's a good point. Once the build tool is running with Console Ninja on, we don't have any knowledge as to where the build tool is planning to save the output, what we can do:
- do not start Console Ninja on the project if it has `bin`/`files` fields by default (user may still start it manually);
- and/or if the project if it has `bin`/`files` fields, and user is starting Console Ninja, we can display a proper warning.

**Comment by ArtemGovorov** [comment]
We have added a modal warning dialog to the latest v0.0.57+ of the extension, so that if `bin`/`files` fields are present then the tool is not started without a permission, and the user is informed what to do to safely use the tool in such projects.
