### ISSUE TITLE
[Feature]: Publish console ninja on open-vsx.org

### ISSUE THREAD

**Issue by mkappelhof** [wallabyjs/console-ninja#86]
### Describe the feature you'd like.

Extensions that are published to the Microsoft Marketplace are [not available](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) for users who use VSCodium (the open source binaries of VS Code without the Microsoft telemetry). 

VSCode uses open-vsx.org as extension gallery so it would be nice if console ninja could also be published there. The docs specify that i can add it, but say it's better [if the maintainers do it themselves](https://github.com/open-vsx/publish-extensions). So here is my question if you want to publish console ninja on open-vsx?

**Comment by ArtemGovorov** [comment]
Unfortunately we cannot publish to the open vsx repository as publishing to the open vsx repository is only available for open-source projects ([see agreement here](https://www.eclipse.org/legal/ECA.php)).

To use Console Ninja in other editors you will need to download the extension from the Microsoft marketplace and then install from VSIX. For example, this is described in the [VS Codium docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace).

https://github.com/wallabyjs/console-ninja/issues/72
