### ISSUE TITLE
[Feature]: Make it available in vscode multi-root workspaces

### ISSUE THREAD

**Issue by denik1981** [wallabyjs/console-ninja#91]
### Describe the feature you'd like.

I have tested console-ninja in a multi-root setup and it is not working for me.
I would suspect this is a missing feature because of the constraint of not knowing which child workspace to listen for. 

To be fairly honest,  I haven't tried a single project that launches 2 supported servers at the same time (for eg, two CN-compatible apps inside  a monorepo started together)

_Side note: The extension works perfectly for me in a non-multiroot workspace_

**Comment by smcenlly** [comment]
Could you please provide us with a sample repo and steps to reproduce your problem?

Also, could you please provide your log output when it's not working for you? Please copy and paste your log output from the `~/.console-ninja/trace.log` file in your user home directory after opening your project and making some changes.

**Comment by denik1981** [comment]
@smcenlly  I will do my best. Hope it helps you!

I will show you an example of a side-by-side case when trying to read a console log (browser destination) in a nextjs app in a non-multi-root workspace and in one that is within a multi-root workspace. For the sake of clarity, I cleared the trace.log between executions. In both cases, the project is the same one and the log is in the same location. In both cases, no other server is started besides the one (nextjs) being used for the purpose of this example.

## **WITHOUT MULTI-ROOT WS**

<img width="571" alt="image" src="https://user-images.githubusercontent.com/66160623/214283938-a2b3c981-7937-45f4-a6cb-e133cd76fc85.png">

<img width="492" alt="image" src="https://user-images.githubusercontent.com/66160623/214284041-fc075dfe-6085-4cb0-a3a7-30f065023d9a.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/66160623/214284167-2d08be54-ca59-46fe-a8cb-7087d8d5cbd9.png">

<img width="833" alt="image" src="https://user-images.githubusercontent.com/66160623/214284320-8f4e258a-083e-480d-9fc8-e7b4aaf41d20.png">

# **WITH MULTI-ROOT WS**

<img width="304" alt="image" src="https://user-images.githubusercontent.com/66160623/214285074-aa597693-3a06-4e06-a3bd-94dfd060f4eb.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/66160623/214285234-54d15a25-a977-4ea3-9b87-87e29faa3637.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/66160623/214285480-de0e359a-1ef7-4b90-be24-979aac87c557.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/66160623/214285858-ed172af8-8f9e-4662-bfbe-3f9a1bbd3152.png">

<img width="521" alt="image" src="https://user-images.githubusercontent.com/66160623/214285922-443b202f-fe7e-4cd9-9789-3e30a324d4d3.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/66160623/214286223-fe293c49-18bf-43b3-a49d-598359491e76.png">

**Comment by denik1981** [comment]
Let me add to the above comment that the current status of **CN** never changes its state no matter how long I wait.

**Comment by ArtemGovorov** [comment]
@denik1981 Thanks for providing the details!

**Comment by juanjcardona13** [comment]
Same for here, waiting... (Thanks for this extension)

**Comment by rmortes** [comment]
Can confirm this is still an issue.

The extension only works for vite projects when said project is the first root folder of the workspace. When the project is later on the list the extension doesn't pick it up, and just stays waiting for the vite to start indefinitely.

**Comment by Soft-Law** [comment]
Also here writing just to confirm this is an issue. I have a workspace with 2 folders: (1) a Python FastAPI server, and (2) a NextJS project. The extension did not work until I moved the NextJS project to being the first root folder of the workspace. When the python folder was 1st and the NextJS folder was 2nd, the extension status registered as inactive and waiting for a NextJS instance to start.

I believe adding a note to the ReadME may be helpful for others until this is resolved.

Otherwise, love the extension. Thank you guys for your hard work.

**Comment by ArtemGovorov** [comment]
We have added the Console Ninja `Select Multi-Root Workspace Project` command that allows to select the project from the multi-root workspace to run the tool on. 

We've also created the feature request to support running Console Ninja on multiple multi-root workspace projects at the same time: https://github.com/wallabyjs/console-ninja/issues/127.
