### ISSUE TITLE
[Feature]: Cypress + esbuild

### ISSUE THREAD

**Issue by darioprinc** [wallabyjs/console-ninja#95]
### Describe the feature you'd like.

Hi, the product looks fantastic, can't wait to use it. What's making it impossible at this moment is missing [**esbuild**](https://esbuild.github.io/) bundler support. Specifically we are using Cypress where we replaced Webpack (running under the hood originally) with esbuild. 

Any plans to add esbuild to the list of tools?

Cheers and keep up the good work!

**Comment by smcenlly** [comment]
Can you please provide us with a sample repo that has `Cypress` configured to use `esbuild`?

**Comment by darioprinc** [comment]
hi @smcenlly, sorry for the delay - reproducible example here:

[cypress-sample-repo.zip](https://github.com/wallabyjs/console-ninja/files/11431614/cypress-sample-repo.zip)

run: 
```
yarn
yarn cypress:open
```

also please ignore the grep option, cypress/e2e/react/login.cy.ts will be available to open and run. 
thanks

**Comment by NikGovorov** [comment]
Thanks for providing the sample project. We've added support for `@bahmutov/cypress-esbuild-preprocessor` to version 0.0.120.

**Comment by darioprinc** [comment]
hi @NikGovorov, thank you, however I can't seem to make it log. 

version: v0.0.120
status:
> Console Ninja is 💤 inactive. Console Ninja has scanned your project dependencies, but has not found any tools that are supported.

extension is enabled, dependencies are freshly installed. am I missing anything?

**Comment by NikGovorov** [comment]
![image](https://github.com/wallabyjs/console-ninja/assets/129254/1a16ea41-2768-4dfe-812f-5ab8f32971f3)
Does `node_modules` folder exist on the file system?

**Comment by NikGovorov** [comment]
I've used `npm` to install the dependencies.

**Comment by darioprinc** [comment]
yes, `node_modules` exist. they are located in the root of the project where `cypress` folder lives as well and from where we run Cypress:

![image](https://github.com/wallabyjs/console-ninja/assets/35229102/37f828bc-d6c7-4cf3-8f41-63c11fe79e5a)

there are multiple `node_modules` across the project though, should I point Console Ninja to the relevant one manually? could it be I am doing some action from an incorrect place?

**Comment by NikGovorov** [comment]
Could you please close all instances of VS Code, remove `~/.console-ninja/trace.log` file, reproduce the issue and share the content of `~/.console-ninja/trace.log` file?
What are the differences between your real project with the sample one? Are `@bahmutov/cypress-esbuild-preprocessor`, `esbuild` and `cypress` versions identical?

**Comment by NikGovorov** [comment]
Closing this issue as we haven't heard back. Please provide the details requested and we will re-open the issue.
