### ISSUE TITLE
[Bug]: Does not work with VsCode Neovim or VsCode Vim

### ISSUE THREAD

**Issue by ShoutsAtGoats** [wallabyjs/console-ninja#96]
### What happened?

I'm currently running a Next.js application on my local host, however I am not getting any log from console ninja. It is currently recognizing that Next is running, but it is stuck "waiting for runtime events".

Just fyi, these are log statements that are run on page load and do work in the browser. I believe it is most likely due to the input methods of the plugins when active vs inactive but I wanted to reach out to see if this was something that others have experienced, or if the app is intended to work with the aforementioned plugins running.

btw.. love the extension. Just wish I could use it with vscode neovim like copilot. 
Thanks again

### Version

0.0.70

### Steps to reproduce (or sample repo)

Install Console Ninja.
Install vscode neovim / vim plugin.
Open Next.js project and host on local host. 
Execute console.log statement

### Log output

```shell
logs are blank...
```

**Comment by ArtemGovorov** [comment]
> I believe it is most likely due to the input methods of the plugins when active vs inactive
> Open Next.js project and host on local host.

Likely the issue is not related to vim/neovim plugins, it's likely something related to the specific project structure. Can you please share a sample project where we can reproduce the issue?

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. 

Please reply with a sample project as requested and we will re-open the issue.
