### ISSUE TITLE
[Bug]: No longer works in Remix 1.11.1

### ISSUE THREAD

**Issue by mircosa** [wallabyjs/console-ninja#97]
### What happened?

First, wanted to say I have really enjoyed using Console Ninja it is immensely useful!

I upgraded from Remix 1.8.2 to Remix 1.11.1 and Console Ninja does not work anymore unfortunately.

It is connected to the Remix server but the logs are empty.

This might be related to the changes made in Remix with 1.11 

### Version

The latest version

### Steps to reproduce (or sample repo)

Test Console Ninja with Remix 1.11

### Log output

```shell
n/a
```

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in version 0.0.71.

**Comment by mircosa** [comment]
Awesome, thanks for the quick turnaround!
