### ISSUE TITLE
[Bug]: Uninstalled Code Ninja but hooks injected during building process

### ISSUE THREAD

**Issue by lokhmakov** [wallabyjs/console-ninja#98]
### What happened?

Build process failed because hook of removed console ninja injected.

### Version

0.0.70

### Steps to reproduce (or sample repo)

.

### Log output

```shell
/* build-hook-start *//*00001*/try { require('/Users/xxx/.vscode/extensions/wallabyjs.console-ninja-0.0.70/out/buildHook/index.js').default({tool: 'webpack'}); } catch(e) { try { import('file:///Users/xxx/.vscode/extensions/wallabyjs.console-ninja-0.0.70/out/buildHook/index.js').then(m => m.default.default({tool: 'webpack'})).catch(p => {}) } catch(e) { }}/* build-hook-end */
```

**Comment by smcenlly** [comment]
Thanks for letting us know about the problem.

Console Ninja should be removing its hooks when uninstalled.

If you have uninstalled Console Ninja, to fix your problem, please uninstall and reinstall your `node_modules`.

**Comment by youminkim** [comment]
The log is gone after rebuilding after removal of `.next` directory
